#!/bin/bash

cd -- "$(dirname -- "${BASH_SOURCE:-$0}")" || { echo "Failed to change directory."; exit 1; }

# Java extensions can be outside of JAVA_HOME. Needed for security manager
JAVA_EXTENSIONS_DIR=/usr/java/packages/lib/ext

used_java="unknown"

if [[ -n "$JRE_HOME" ]] && [[ -x "$JRE_HOME/bin/java" ]];  then
    _java="$JRE_HOME/bin/java"
    used_java=$_java
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
    _java="$JAVA_HOME/bin/java"
    used_java=$_java
elif type -p java; then
    _java=java
    used_java="PATH"
else
    echo "--- Probably, you have not installed Java"
    exit 1
fi

if [[ "$_java" ]]; then
    version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
    if [[ "$version" = "9" ]] || [[ "${version:0:2}" == "9." ]]; then
        JAVA_OPTS="$JAVA_OPTS --add-modules java.se.ee --patch-module java.xml.ws.annotation=lib/annotations-api.jar --add-exports=java.xml.ws.annotation/javax.annotation.security=ALL-UNNAMED"
    elif [[ "${version:0:3}" == "1.8" ]]; then
        JAVA_OPTS="$JAVA_OPTS -XX:+UseParNewGC -XX:+UseConcMarkSweepGC"
    elif [[ "${version:0:3}" == "1.7" ]]; then
        JAVA_OPTS="$JAVA_OPTS -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:PermSize=128m -XX:MaxPermSize=512mC"
    fi
fi

if [[ $(uname -s) == "Darwin" ]]; then
  memory=$(sysctl -a | grep hw.memsize | awk '{print $2/1024/1024/1024}')
else
  memory=$(free -g | awk '/Mem:/{print $2}')
fi

if [[ "$CONTAINER" != "true" ]]; then
  if [[ ${memory} -ge 48 ]]; then
    _JAVA_MEMORY="-Xms4g -Xmx42g"
  elif [[ ${memory} -ge 32 ]]; then
    _JAVA_MEMORY="-Xms4g -Xmx28g"
  elif [[ ${memory} -ge 24 ]]; then
    _JAVA_MEMORY="-Xms4g -Xmx20g"
  elif [[ ${memory} -ge 16 ]]; then
    _JAVA_MEMORY="-Xms4g -Xmx12g"
  elif [[ ${memory} -ge 12 ]]; then
    _JAVA_MEMORY="-Xms4g -Xmx10g"
  elif [[ ${memory} -ge 8 ]]; then
    _JAVA_MEMORY="-Xms4g -Xmx7g"
  elif [[ _memory -ge 6 ]]; then
    _JAVA_MEMORY="-Xms3g -Xmx5g"
  elif [[ ${memory} -ge 4 ]]; then
    _JAVA_MEMORY="-Xms2g -Xmx3g"
  else
    _JAVA_MEMORY="-Xms512m -Xmx2g"
  fi
fi



[[ -f demo-java.policy ]] && JETTY_OPTS="$JETTY_OPTS -Djava.security.manager -Djava.security.policy=demo-java.policy -Djava.extensions=$JAVA_EXTENSIONS_DIR"

export JAVA_OPTS="$JAVA_OPTS $_JAVA_MEMORY"
export JETTY_OPTS="-DDEMO=DEMO -Dopenl.home=./openl-demo -Dh2.bindAddress=localhost $JETTY_OPTS"
export JAVA_OPTIONS="$JAVA_OPTS $JETTY_OPTS $JAVA_OPTIONS"

echo "### Starting OpenL Tablets DEMO ..."
echo "Memory size (gigabytes):    $memory"
echo "Java version:               $version"
echo "Java found in:              $used_java"
echo "Using JAVA_OPTIONS:         $JAVA_OPTIONS"


findDirectory()
{
  local L OP=$1
  shift
  for L in "$@"; do
    [ "$OP" "$L" ] || continue
    printf %s "$L"
    break
  done
}

TMPDIR=${TMPDIR:-/tmp}
JETTY_HOME=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
JETTY_BASE=$JETTY_HOME

if [ -z "$JETTY_RUN" ]
then
  JETTY_RUN=$(findDirectory -w /var/run /usr/var/run $JETTY_BASE /tmp)/jetty
  [ -d "$JETTY_RUN" ] || mkdir $JETTY_RUN
fi

#####################################################
# Find a pid and state file
#####################################################
if [ -z "$JETTY_PID" ]
then
  JETTY_PID="$JETTY_RUN/jetty.pid"
fi

running()
{
  if [ -f "$1" ]
  then
    local PID=$(cat "$1" 2>/dev/null) || return 1
    kill -0 "$PID" 2>/dev/null
    return
  fi
  rm -f "$1"
  return 1
}

if running $JETTY_PID
then
  echo "Already Running $(cat $JETTY_PID)!"
  exit 1
fi

("$_java" $JAVA_OPTIONS -Djetty.home="$JETTY_HOME" -Djetty.base="$JETTY_HOME" -Djava.io.tmpdir="$TMPDIR" -jar "$JETTY_HOME/start.jar" jetty.state=jetty.state jetty-started.xml > /dev/null) &
disown $!
echo $! > $JETTY_PID
