<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="openl"
    nsURI="http://exigengroup.com/openl" nsPrefix="openl">
  <eClassifiers xsi:type="ecore:EClass" name="RuleSetFile" eSuperTypes="../../../plugin/com.exigen.eclipse.common.model/models/common.ecore#//primitives/BaseRootModelElement ../../../plugin/com.exigen.eclipse.common.model/models/common.ecore#//components/ComponentDefinition">
    <eAnnotations source="http://www.exigengroup.com/common/Component">
      <details key="builder" value="com.exigen.openl.component.RuleComponentBuilder"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="excelResourceReference"
        eType="#//ExcelResourceReference" changeable="false" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initParameters" upperBound="-1"
        eType="ecore:EClass ../../../plugin/com.exigen.eclipse.common.model/models/common.ecore#//components/InitParameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ruleSets" upperBound="-1"
        eType="#//RuleSet" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuleSet" eSuperTypes="../../../plugin/com.exigen.eclipse.common.model/models/common.ecore#//components/java/JavaMethodOperationDefinition">
    <eAnnotations source="http://www.exigengroup.com/common/Component">
      <details key="executor" value="com.exigen.openl.component.RuleSetExecutor"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ExcelResourceReference" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EClass" name="RuleSetParameter" eSuperTypes="../../../plugin/com.exigen.eclipse.common.model/models/common.ecore#//components/java/JavaMethodParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="RuleSetReturn" eSuperTypes="../../../plugin/com.exigen.eclipse.common.model/models/common.ecore#//components/java/JavaMethodReturn"/>
</ecore:EPackage>
