# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    cooldown:
      default-days: 7
      include:
        - "software.amazon.*"

  - package-ecosystem: "npm"
    directories:
      - "STUDIO/studio-ui/"
    schedule:
      interval: "daily"
    groups:
      ESLint:
        patterns:
          - "*eslint*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
