site_name: OpenL Tablets
site_url: https://openldocs.readthedocs.io/en/latest/
edit_uri: edit/main/Docs/
nav:
    - Installation Guide: documentation/guides/installation_guide.md
    - Demo Package Guide: documentation/guides/demo_package_guide.md
    - For Business Users:
      - Reference Guide:
        - Introduction:
          - Preface: documentation/guides/reference-guide/introduction/preface.md
          - What Is OpenL Tablets?: documentation/guides/reference-guide/introduction/what-is-openl-tablets.md
          - Basic Concepts: documentation/guides/reference-guide/introduction/basic-concepts.md
          - System Overview: documentation/guides/reference-guide/introduction/system-overview.md
          - Installing OpenL Tablets: documentation/guides/reference-guide/introduction/installing-openl-tablets.md
          - Tutorials and Examples: documentation/guides/reference-guide/introduction/tutorials-and-examples.md
        - Working with OpenL Tables:
          - Table Recognition Algorithm: documentation/guides/reference-guide/working-with-openl-tables/table-recognition-algorithm.md
          - Naming Conventions: documentation/guides/reference-guide/working-with-openl-tables/naming-conventions.md
          - Table Types:
            - Decision Table:
              - Overview and Structure: documentation/guides/reference-guide/working-with-openl-tables/table-types/decision-table/decision-table-overview-and-structure.md
              - Interpretation: documentation/guides/reference-guide/working-with-openl-tables/table-types/decision-table/decision-table-interpretation.md
              - Simple and Smart Rules Tables:
                - Overview: documentation/guides/reference-guide/working-with-openl-tables/table-types/decision-table/simple-and-smart-rules-tables-overview.md
                - Simple Rules Tables: documentation/guides/reference-guide/working-with-openl-tables/table-types/decision-table/simple-rules-tables.md
                - Smart Rules Tables: documentation/guides/reference-guide/working-with-openl-tables/table-types/decision-table/smart-rules-tables.md
                - Multiple Return Columns: documentation/guides/reference-guide/working-with-openl-tables/table-types/decision-table/multiple-return-columns-in-smart-rules-tables.md
                - Custom Data Type Results: documentation/guides/reference-guide/working-with-openl-tables/table-types/decision-table/result-of-custom-data-type-in-smart-and-simple-rules-tables.md
              - Lookup Tables:
                - Overview: documentation/guides/reference-guide/working-with-openl-tables/table-types/decision-table/lookup-tables-overview.md
                - Simple Lookup Tables: documentation/guides/reference-guide/working-with-openl-tables/table-types/decision-table/simple-lookup-tables.md
                - Smart Lookup Tables: documentation/guides/reference-guide/working-with-openl-tables/table-types/decision-table/smart-lookup-tables.md
              - External Tables Usage: documentation/guides/reference-guide/working-with-openl-tables/table-types/decision-table/external-tables-usage-in-smart-decision-tables.md
              - Ranges and Arrays: documentation/guides/reference-guide/working-with-openl-tables/table-types/decision-table/ranges-and-arrays-in-smart-and-simple-decision-tables.md
              - Rules Tables: documentation/guides/reference-guide/working-with-openl-tables/table-types/decision-table/rules-tables.md
              - Collecting Results: documentation/guides/reference-guide/working-with-openl-tables/table-types/decision-table/collecting-results-in-decision-table.md
              - Local Parameters: documentation/guides/reference-guide/working-with-openl-tables/table-types/decision-table/local-parameters-in-decision-table.md
              - Transposed Tables: documentation/guides/reference-guide/working-with-openl-tables/table-types/decision-table/transposed-decision-tables.md
              - Representing Values: documentation/guides/reference-guide/working-with-openl-tables/table-types/decision-table/representing-values-of-different-types.md
              - Using Calculations: documentation/guides/reference-guide/working-with-openl-tables/table-types/decision-table/using-calculations-in-table-cells.md
              - Referencing Attributes: documentation/guides/reference-guide/working-with-openl-tables/table-types/decision-table/referencing-attributes.md
              - Calling Tables: documentation/guides/reference-guide/working-with-openl-tables/table-types/decision-table/calling-a-table-from-another-table.md
              - Return Column Referents: documentation/guides/reference-guide/working-with-openl-tables/table-types/decision-table/using-referents-from-return-column-cells.md
              - Rule Names and Numbers: documentation/guides/reference-guide/working-with-openl-tables/table-types/decision-table/using-rule-names-and-rule-numbers-in-the-return-column.md
              - References to Expressions: documentation/guides/reference-guide/working-with-openl-tables/table-types/decision-table/using-references-to-expressions.md
            - Datatype Table:
              - Introduction: documentation/guides/reference-guide/working-with-openl-tables/table-types/datatype-table/introducing-datatype-tables.md
              - Inheritance: documentation/guides/reference-guide/working-with-openl-tables/table-types/datatype-table/inheritance-in-data-types.md
              - Vocabulary Data Types: documentation/guides/reference-guide/working-with-openl-tables/table-types/datatype-table/vocabulary-data-types.md
            - Data Table:
              - Simple Data Tables: documentation/guides/reference-guide/working-with-openl-tables/table-types/data-table/using-simple-data-tables.md
              - Advanced Data Tables: documentation/guides/reference-guide/working-with-openl-tables/table-types/data-table/using-advanced-data-tables.md
              - List and Map Fields: documentation/guides/reference-guide/working-with-openl-tables/table-types/data-table/specifying-data-in-data-tables-with-list-and-map-fields.md
              - Aggregated Objects: documentation/guides/reference-guide/working-with-openl-tables/table-types/data-table/specifying-data-for-aggregated-objects.md
              - Data Integrity: documentation/guides/reference-guide/working-with-openl-tables/table-types/data-table/ensuring-data-integrity.md
            - Test Table:
              - Understanding Test Tables: documentation/guides/reference-guide/working-with-openl-tables/table-types/test-table/understanding-test-tables.md
              - Context Variables: documentation/guides/reference-guide/working-with-openl-tables/table-types/test-table/context-variables-available-in-test-tables.md
              - Testing SpreadsheetResult: documentation/guides/reference-guide/working-with-openl-tables/table-types/test-table/creating-a-test-table-for-a-spreadsheet-or-decision-table-with-spreadsheetresult-as-input-parameter.md
            - Spreadsheet Table:
              - Parsing: documentation/guides/reference-guide/working-with-openl-tables/table-types/spreadsheet-table/parsing-a-spreadsheet-table.md
              - Accessing Result Cells: documentation/guides/reference-guide/working-with-openl-tables/table-types/spreadsheet-table/accessing-spreadsheet-result-cells.md
              - Using Ranges: documentation/guides/reference-guide/working-with-openl-tables/table-types/spreadsheet-table/using-ranges-in-spreadsheet-table.md
              - Auto Type Discovery: documentation/guides/reference-guide/working-with-openl-tables/table-types/spreadsheet-table/auto-type-discovery-usage.md
              - Custom Spreadsheet Result: documentation/guides/reference-guide/working-with-openl-tables/table-types/spreadsheet-table/custom-spreadsheet-result.md
              - Output Customization: documentation/guides/reference-guide/working-with-openl-tables/table-types/spreadsheet-table/spreadsheet-result-output-customization.md
              - Testing: documentation/guides/reference-guide/working-with-openl-tables/table-types/spreadsheet-table/testing-spreadsheet-result.md
            - Configuration Table:
              - Description: documentation/guides/reference-guide/working-with-openl-tables/table-types/configuration-table/configuration-table-description.md
              - Module Dependencies: documentation/guides/reference-guide/working-with-openl-tables/table-types/configuration-table/defining-dependencies-between-modules-in-the-configuration-table.md
            - Run Table: documentation/guides/reference-guide/working-with-openl-tables/table-types/run-table.md
            - Method Table: documentation/guides/reference-guide/working-with-openl-tables/table-types/method-table.md
            - Properties Table: documentation/guides/reference-guide/working-with-openl-tables/table-types/properties-table.md
            - TBasic Table: documentation/guides/reference-guide/working-with-openl-tables/table-types/tbasic-table.md
            - Column Match Table: documentation/guides/reference-guide/working-with-openl-tables/table-types/column-match-table.md
            - Constants Table: documentation/guides/reference-guide/working-with-openl-tables/table-types/constants-table.md
            - Table Part: documentation/guides/reference-guide/working-with-openl-tables/table-types/table-part.md
          - Table Properties:
            - Category and Module Level: documentation/guides/reference-guide/working-with-openl-tables/table-properties/category-and-module-level-properties.md
            - Default Value: documentation/guides/reference-guide/working-with-openl-tables/table-properties/default-value.md
            - System Properties: documentation/guides/reference-guide/working-with-openl-tables/table-properties/system-properties.md
            - Properties for Specific Types: documentation/guides/reference-guide/working-with-openl-tables/table-properties/properties-for-a-particular-table-type.md
            - Rule Versioning: documentation/guides/reference-guide/working-with-openl-tables/table-properties/rule-versioning.md
            - Info Properties: documentation/guides/reference-guide/working-with-openl-tables/table-properties/info-properties.md
            - Dev Properties: documentation/guides/reference-guide/working-with-openl-tables/table-properties/dev-properties.md
            - Properties in File Name: documentation/guides/reference-guide/working-with-openl-tables/table-properties/properties-defined-in-the-file-name.md
            - Properties in Folder Name: documentation/guides/reference-guide/working-with-openl-tables/table-properties/properties-defined-in-the-folder-name.md
            - Keywords Usage: documentation/guides/reference-guide/working-with-openl-tables/table-properties/keywords-usage-in-a-file-name.md
        - Functions and Data Types:
          - Working with Arrays: documentation/guides/reference-guide/openl_tablets_functions_and_supported_data_types/working-with-arrays.md
          - Working with Data Types: documentation/guides/reference-guide/openl_tablets_functions_and_supported_data_types/working-with-data-types.md
          - Working with Functions: documentation/guides/reference-guide/openl_tablets_functions_and_supported_data_types/working-with-functions.md
        - Working with Projects:
          - Project Structure: documentation/guides/reference-guide/working_with_projects/project-structure.md
          - Runtime Context Management: documentation/guides/reference-guide/working_with_projects/rules-runtime-context-management-from-rules.md
          - Project, Module, and Rule Dependencies: documentation/guides/reference-guide/working_with_projects/project,-module,-and-rule-dependencies.md
          - Project Localization: documentation/guides/reference-guide/working_with_projects/project-localization.md
        - Appendices:
          - Introduction to BEX: documentation/guides/reference-guide/appendices/introduction-to-bex.md
          - Keywords: documentation/guides/reference-guide/appendices/keywords.md
          - Simplifying Expressions: documentation/guides/reference-guide/appendices/simplifying-expressions.md
          - Operators: documentation/guides/reference-guide/appendices/operators-used-in-openl-tablets.md
          - Math Functions: documentation/guides/reference-guide/appendices/math-functions.md
          - Array Functions: documentation/guides/reference-guide/appendices/array-functions.md
          - Date Functions: documentation/guides/reference-guide/appendices/date-functions.md
          - String Functions: documentation/guides/reference-guide/appendices/string-functions.md
          - Special Functions: documentation/guides/reference-guide/appendices/special-functions.md
      - OpenL Studio User Guide: documentation/guides/webstudio_user_guide.md
    - For Developers:
      - Rule Services Usage and Customization Guide: documentation/guides/rule_services_usage_and_customization_guide.md
      - Developer Guide: documentation/guides/developer_guide.md
      - Activiti Integration Guide: documentation/guides/activiti_integration_guide.md
    - About OpenL: about.md
    - Download PDFs: PDFs.md

theme:
    name: material
    navigation_depth: 8
    logo: assets/logo.svg
    favicon: assets/logo.svg
    features:
    - content.action.edit
    - content.action.view
    - navigation.expand
    - navigation.indexes

repo_url: https://github.com/openl-tablets/openl-tablets/
repo_name: openl-tablets/openl-tablets

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.superfences
  - toc:
      permalink: True

extra_css:
    - css/extra.css
