/* Generated By:JavaCC: Do not edit this line. BExGrammarConstants.java */
package org.openl.grammars.bexgrammar;

public interface BExGrammarConstants {

  int EOF = 0;
  int OR = 6;
  int AND = 7;
  int NOT = 8;
  int ABSTRACT = 9;
  int BREAK = 10;
  int CALCULATE = 11;
  int CASE = 12;
  int CATCH = 13;
  int CONST = 14;
  int CONTINUE = 15;
  int _DEFAULT = 16;
  int DO = 17;
  int ELSE = 18;
  int EXTENDS = 19;
  int FALSE = 20;
  int FINAL = 21;
  int FINALLY = 22;
  int FOR = 23;
  int GOTO = 24;
  int IF = 25;
  int PLUSSTR = 26;
  int IMPLEMENTS = 27;
  int IMPORT = 28;
  int INSTANCEOF = 29;
  int INTERFACE = 30;
  int NATIVE = 31;
  int NEW = 32;
  int NULL = 33;
  int PACKAGE = 34;
  int PRIVATE = 35;
  int PROTECTED = 36;
  int PUBLIC = 37;
  int RETURN = 38;
  int STATIC = 39;
  int SUPER = 40;
  int SWITCH = 41;
  int SYNCHRONIZED = 42;
  int THROW = 43;
  int THROWS = 44;
  int TRANSIENT = 45;
  int TRUE = 46;
  int TRY = 47;
  int VOID = 48;
  int VOLATILE = 49;
  int WHILE = 50;
  int OF = 51;
  int THE = 52;
  int WHERE = 53;
  int IS = 54;
  int LESS = 55;
  int THAN = 56;
  int LPAREN = 57;
  int RPAREN = 58;
  int LBRACE = 59;
  int RBRACE = 60;
  int LBRACKET = 61;
  int RBRACKET = 62;
  int SEMICOLON = 63;
  int COMMA = 64;
  int DOT = 65;
  int DDOT = 66;
  int ASSIGN = 67;
  int GT = 68;
  int LT = 69;
  int BANG = 70;
  int TILDE = 71;
  int HOOK = 72;
  int COLON = 73;
  int EQ = 74;
  int LE = 75;
  int GE = 76;
  int NE = 77;
  int BOOL_OR = 78;
  int BOOL_AND = 79;
  int INCR = 80;
  int DECR = 81;
  int PLUS = 82;
  int MINUS = 83;
  int STAR = 84;
  int SLASH = 85;
  int BIT_AND = 86;
  int BIT_OR = 87;
  int BIT_XOR = 88;
  int REM = 89;
  int LSHIFT = 90;
  int RSIGNEDSHIFT = 91;
  int RUNSIGNEDSHIFT = 92;
  int PLUSASSIGN = 93;
  int MINUSASSIGN = 94;
  int STARASSIGN = 95;
  int SLASHASSIGN = 96;
  int ANDASSIGN = 97;
  int ORASSIGN = 98;
  int XORASSIGN = 99;
  int REMASSIGN = 100;
  int LSHIFTASSIGN = 101;
  int RSIGNEDSHIFTASSIGN = 102;
  int RUNSIGNEDSHIFTASSIGN = 103;
  int EXP = 104;
  int IMPL = 105;
  int INTEGER_LITERAL = 106;
  int DECIMAL_LITERAL = 107;
  int HEX_LITERAL = 108;
  int OCTAL_LITERAL = 109;
  int FP_LITERAL1 = 110;
  int FP_LITERAL2 = 111;
  int FLOATING_POINT_LITERAL = 112;
  int BUSINESS_INTEGER_LITERAL = 113;
  int PERCENT_LITERAL = 114;
  int EXPONENT = 115;
  int CHARACTER_LITERAL = 116;
  int STRING_LITERAL = 117;
  int IDENTIFIER = 118;
  int LETTER = 119;
  int DIGIT = 120;
  int LABEL = 121;
  int SINGLE_LINE_COMMENT = 124;
  int FORMAL_COMMENT = 125;
  int MULTI_LINE_COMMENT = 126;

  int DEFAULT = 0;
  int IN_FORMAL_COMMENT = 1;
  int IN_MULTI_LINE_COMMENT = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"abstract\"",
    "\"break\"",
    "\"Calculate\"",
    "\"case\"",
    "\"catch\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"plus\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"interface\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"of\"",
    "\"the\"",
    "\"where\"",
    "\"is\"",
    "\"less\"",
    "\"than\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"..\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"**\"",
    "\"->\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FP_LITERAL1>",
    "<FP_LITERAL2>",
    "<FLOATING_POINT_LITERAL>",
    "<BUSINESS_INTEGER_LITERAL>",
    "<PERCENT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<LABEL>",
    "<token of kind 122>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 127>",
    "\"equals to\"",
    "\"is same as\"",
    "\"does not equal to\"",
    "\"is different from\"",
    "\"is less than\"",
    "\"is more than\"",
    "\"is less or equal\"",
    "\"is no more than\"",
    "\"is in\"",
    "\"is more or equal\"",
    "\"is no less than\"",
  };

}
