

cell:  grid-cell | merged-cell


empty-cell:  cell (content == "")

non-empty-cell: cell (content != "")


table: non-empty-cell > column-header \/ row-header

column-header: non-empty-cell | merged-cell    

row-header: non-empty-cell | merged-cell

table decision-table:  decision-table-header decision-table-rows     

cell decision-table-header: ("DT" | "Rules") MethodHeader   


decision-table-rows: condition-row | action-row | comment-row

row condition-row:  condition-header condition-code condition-parameters 

row action-row:  action-header action-code parameter-definition parameter-display (data-cell)* 

cell condition-header:  ConditionName
cell condition-code:   ConditionCode


condition-parameters: decision-table-parameters


table decision-table-parameters:  parameter-row

row parameter-row:   parameter-definition parameter-display (parameter-data)*
 
cell parameter-definition: ParameterType ParameterName
cell parameter-display:   StringLiteral
parameter-data:  scalar-parameter-data | vector-parameter-data 
cell scalar-parameter-data: StringLiteral | empty-cell
column vector-parameter-data: (scalar-parameter-data)*
    

data-table:  data-table-header data-table-rows