/* Generated By:JavaCC: Do not edit this line. BExGrammarConstants.java */
package org.openl.grammars.bex;

public interface BExGrammarConstants {

  int EOF = 0;
  int OR = 6;
  int AND = 7;
  int ABSTRACT = 8;
  int BREAK = 9;
  int CASE = 10;
  int CATCH = 11;
  int CONST = 12;
  int CONTINUE = 13;
  int _DEFAULT = 14;
  int DO = 15;
  int ELSE = 16;
  int EXTENDS = 17;
  int FALSE = 18;
  int FINAL = 19;
  int FINALLY = 20;
  int FOR = 21;
  int GOTO = 22;
  int IF = 23;
  int PLUSSTR = 24;
  int IMPLEMENTS = 25;
  int IMPORT = 26;
  int INSTANCEOF = 27;
  int INTERFACE = 28;
  int NATIVE = 29;
  int NEW = 30;
  int NULL = 31;
  int PACKAGE = 32;
  int PRIVATE = 33;
  int PROTECTED = 34;
  int PUBLIC = 35;
  int RETURN = 36;
  int STATIC = 37;
  int SUPER = 38;
  int SWITCH = 39;
  int SYNCHRONIZED = 40;
  int THROW = 41;
  int THROWS = 42;
  int TRANSIENT = 43;
  int TRUE = 44;
  int TRY = 45;
  int VOID = 46;
  int VOLATILE = 47;
  int WHILE = 48;
  int LPAREN = 49;
  int RPAREN = 50;
  int LBRACE = 51;
  int RBRACE = 52;
  int LBRACKET = 53;
  int RBRACKET = 54;
  int SEMICOLON = 55;
  int COMMA = 56;
  int DOT = 57;
  int ASSIGN = 58;
  int GT = 59;
  int LT = 60;
  int BANG = 61;
  int TILDE = 62;
  int HOOK = 63;
  int COLON = 64;
  int EQ = 65;
  int LE = 66;
  int GE = 67;
  int NE = 68;
  int SC_OR = 69;
  int SC_AND = 70;
  int INCR = 71;
  int DECR = 72;
  int PLUS = 73;
  int MINUS = 74;
  int STAR = 75;
  int SLASH = 76;
  int BIT_AND = 77;
  int BIT_OR = 78;
  int XOR = 79;
  int REM = 80;
  int LSHIFT = 81;
  int RSIGNEDSHIFT = 82;
  int RUNSIGNEDSHIFT = 83;
  int PLUSASSIGN = 84;
  int MINUSASSIGN = 85;
  int STARASSIGN = 86;
  int SLASHASSIGN = 87;
  int ANDASSIGN = 88;
  int ORASSIGN = 89;
  int XORASSIGN = 90;
  int REMASSIGN = 91;
  int LSHIFTASSIGN = 92;
  int RSIGNEDSHIFTASSIGN = 93;
  int RUNSIGNEDSHIFTASSIGN = 94;
  int EXP = 95;
  int IMPL = 96;
  int INTEGER_LITERAL = 97;
  int DECIMAL_LITERAL = 98;
  int HEX_LITERAL = 99;
  int OCTAL_LITERAL = 100;
  int FLOATING_POINT_LITERAL = 101;
  int BUSINESS_INTEGER_LITERAL = 102;
  int PERCENT_LITERAL = 103;
  int EXPONENT = 104;
  int CHARACTER_LITERAL = 105;
  int STRING_LITERAL = 106;
  int IDENTIFIER = 107;
  int LETTER = 108;
  int DIGIT = 109;
  int SINGLE_LINE_COMMENT = 112;
  int FORMAL_COMMENT = 113;
  int MULTI_LINE_COMMENT = 114;

  int DEFAULT = 0;
  int IN_FORMAL_COMMENT = 1;
  int IN_MULTI_LINE_COMMENT = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"or\"",
    "\"and\"",
    "\"abstract\"",
    "\"break\"",
    "\"case\"",
    "\"catch\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"plus\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"interface\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"**\"",
    "\"->\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<BUSINESS_INTEGER_LITERAL>",
    "<PERCENT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<token of kind 110>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 115>",
    "\"of the\"",
    "\"is less than\"",
    "\"is more than\"",
    "\"is less or equal\"",
    "\"is no more than\"",
    "\"is in\"",
    "\"is more or equal\"",
    "\"is no less than\"",
  };

}
