-- Security schema and data an H2 database carries after OpenL Tablets 5.27.15 has initialized it, the
-- oldest release the change log converts. The statements reproduce what the migration tool of that release
-- left behind, including its own history table, so a test can start from a database handed over by it.
--
-- The releases that follow are layered on top of this one, each by a script of its own.

CREATE TABLE OpenL_Users (
    loginName VARCHAR(50) NOT NULL,
    password VARCHAR(128),
    firstName VARCHAR(50),
    surname VARCHAR(50),
    email VARCHAR(254),
    displayName VARCHAR(64),
    flags INTEGER DEFAULT 0 NOT NULL,
    PRIMARY KEY (loginName)
);

CREATE TABLE OpenL_Groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    groupName VARCHAR(65) NOT NULL UNIQUE,
    description VARCHAR(200),
    PRIMARY KEY (id)
);

CREATE TABLE OpenL_Group_Authorities (
    groupID BIGINT NOT NULL,
    authority VARCHAR(50) NOT NULL,
    PRIMARY KEY (groupID, authority),
    CONSTRAINT fk_OpenL_Group_Authorities1 FOREIGN KEY (groupID) REFERENCES OpenL_Groups (id) ON DELETE CASCADE
);

CREATE TABLE OpenL_User2Group (
    loginName VARCHAR(50) NOT NULL,
    groupID BIGINT NOT NULL,
    PRIMARY KEY (loginName, groupID),
    CONSTRAINT fk_OpenL_User2Group1 FOREIGN KEY (loginName) REFERENCES OpenL_Users (loginName) ON DELETE CASCADE,
    CONSTRAINT fk_OpenL_User2Group2 FOREIGN KEY (groupID) REFERENCES OpenL_Groups (id) ON DELETE CASCADE
);

CREATE TABLE OpenL_UserSettings (
    loginName VARCHAR(50) NOT NULL,
    settingKey VARCHAR(64) NOT NULL,
    settingValue VARCHAR(16) NOT NULL,
    PRIMARY KEY (loginName, settingKey),
    CONSTRAINT fk_OpenL_UserSettings1 FOREIGN KEY (loginName) REFERENCES OpenL_Users (loginName) ON DELETE CASCADE
);

CREATE TABLE OpenL_External_Groups (
    loginName VARCHAR(50) NOT NULL,
    groupName VARCHAR(65) NOT NULL,
    PRIMARY KEY (loginName, groupName),
    CONSTRAINT fk_OpenL_External_Groups1 FOREIGN KEY (loginName) REFERENCES OpenL_Users (loginName) ON DELETE CASCADE
);

CREATE TABLE OpenL_Tag_Types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    extensible BOOLEAN NOT NULL,
    nullable BOOLEAN NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uni_OpenL_Tag_Types1 UNIQUE (name)
);

CREATE TABLE OpenL_Tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tag_type_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_OpenL_Tags1 FOREIGN KEY (tag_type_id) REFERENCES OpenL_Tag_Types (id) ON DELETE CASCADE,
    CONSTRAINT uni_OpenL_Tags1 UNIQUE (tag_type_id, name)
);

CREATE TABLE OpenL_Projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    repository_id VARCHAR(255) NOT NULL,
    project_path VARCHAR(1000) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE OpenL_Project_Tags (
    project_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (project_id, tag_id),
    CONSTRAINT fk_OpenL_Project_Tags1 FOREIGN KEY (project_id) REFERENCES OpenL_Projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_OpenL_Project_Tags2 FOREIGN KEY (tag_id) REFERENCES OpenL_Tags (id) ON DELETE CASCADE
);

CREATE TABLE OpenL_Tag_Templates (
    template VARCHAR(255) NOT NULL,
    priority INTEGER,
    PRIMARY KEY (template),
    CONSTRAINT uni_OpenL_Tag_Templates1 UNIQUE (priority)
);

CREATE TABLE OPENL_LOCK (
    LOCK_KEY VARCHAR(36) NOT NULL,
    REGION VARCHAR(100) NOT NULL,
    CLIENT_ID VARCHAR(36),
    CREATED_DATE TIMESTAMP NOT NULL,
    CONSTRAINT OPENL_LOCK_PK PRIMARY KEY (LOCK_KEY, REGION)
);

CREATE SEQUENCE acl_sid_sequence START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE acl_class_sequence START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE acl_object_identity_sequence START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE acl_entry_sequence START WITH 1 INCREMENT BY 1 NOMAXVALUE;

CREATE TABLE acl_sid (
    id BIGINT DEFAULT NEXT VALUE FOR acl_sid_sequence NOT NULL PRIMARY KEY,
    principal BOOLEAN NOT NULL,
    sid VARCHAR(255) NOT NULL,
    CONSTRAINT unique_uk_1 UNIQUE (sid, principal)
);

CREATE TABLE acl_class (
    id BIGINT DEFAULT NEXT VALUE FOR acl_class_sequence NOT NULL PRIMARY KEY,
    class VARCHAR(2000) NOT NULL,
    class_id_type VARCHAR(2000),
    CONSTRAINT unique_uk_2 UNIQUE (class)
);

CREATE TABLE acl_object_identity (
    id BIGINT DEFAULT NEXT VALUE FOR acl_object_identity_sequence NOT NULL PRIMARY KEY,
    object_id_class BIGINT NOT NULL,
    object_id_identity VARCHAR(65535) NOT NULL,
    parent_object BIGINT,
    owner_sid BIGINT,
    entries_inheriting BOOLEAN NOT NULL,
    CONSTRAINT unique_uk_3 UNIQUE (object_id_class, object_id_identity),
    CONSTRAINT foreign_fk_1 FOREIGN KEY (parent_object) REFERENCES acl_object_identity (id),
    CONSTRAINT foreign_fk_2 FOREIGN KEY (object_id_class) REFERENCES acl_class (id),
    CONSTRAINT foreign_fk_3 FOREIGN KEY (owner_sid) REFERENCES acl_sid (id)
);

CREATE TABLE acl_entry (
    id BIGINT DEFAULT NEXT VALUE FOR acl_entry_sequence NOT NULL PRIMARY KEY,
    acl_object_identity BIGINT NOT NULL,
    ace_order INTEGER NOT NULL,
    sid BIGINT NOT NULL,
    mask INTEGER NOT NULL,
    granting BOOLEAN NOT NULL,
    audit_success BOOLEAN NOT NULL,
    audit_failure BOOLEAN NOT NULL,
    CONSTRAINT unique_uk_4 UNIQUE (acl_object_identity, ace_order),
    CONSTRAINT foreign_fk_4 FOREIGN KEY (acl_object_identity) REFERENCES acl_object_identity (id),
    CONSTRAINT foreign_fk_5 FOREIGN KEY (sid) REFERENCES acl_sid (id)
);

INSERT INTO OpenL_Groups (groupName) VALUES ('Administrators'), ('Viewers'), ('Developers'), ('Testers'), ('Deployers'), ('Analysts');
INSERT INTO OpenL_Group_Authorities (groupID, authority) SELECT id, 'ADMIN' FROM OpenL_Groups WHERE groupName = 'Administrators';

INSERT INTO acl_sid (principal, sid) VALUES (FALSE, 'ADMIN'), (FALSE, 'Deployers'), (FALSE, 'Developers'), (FALSE, 'Testers'), (FALSE, 'Viewers'), (FALSE, 'Analysts');
INSERT INTO acl_class (class, class_id_type) VALUES
    ('org.openl.security.acl.repository.Root', 'java.lang.String'),
    ('org.openl.security.acl.repository.ProjectArtifact', 'java.lang.String'),
    ('org.openl.security.acl.repository.DeploymentProjectArtifact', 'java.lang.String'),
    ('org.openl.security.acl.repository.RepositoryObjectIdentity', 'java.lang.String');

INSERT INTO acl_object_identity (object_id_class, object_id_identity, parent_object, owner_sid, entries_inheriting)
SELECT c.id, r.root, NULL, s.id, TRUE
FROM acl_class c, acl_sid s, (SELECT '1' AS root UNION ALL SELECT '2' UNION ALL SELECT '3') r
WHERE c.class = 'org.openl.security.acl.repository.Root' AND s.sid = 'ADMIN' AND s.principal = FALSE;

INSERT INTO acl_entry (acl_object_identity, ace_order, sid, mask, granting, audit_success, audit_failure)
SELECT o.id, e.ace_order, s.id, e.mask, TRUE, FALSE, FALSE
FROM (
        SELECT '1', 'Developers', 33554448, 0
    UNION ALL SELECT '1', 'Developers', 50331664, 1
    UNION ALL SELECT '1', 'Developers', 67108884, 2
    UNION ALL SELECT '1', 'Developers', 83886088, 3
    UNION ALL SELECT '1', 'Developers', 100663328, 4
    UNION ALL SELECT '1', 'Testers', 201326592, 5
    UNION ALL SELECT '1', 'Testers', 218103808, 6
    UNION ALL SELECT '1', 'Viewers', 16777217, 7
    UNION ALL SELECT '2', 'Deployers', 33554448, 8
    UNION ALL SELECT '2', 'Deployers', 50331664, 9
    UNION ALL SELECT '2', 'Deployers', 67108884, 10
    UNION ALL SELECT '2', 'Deployers', 83886088, 11
    UNION ALL SELECT '2', 'Deployers', 100663328, 12
    UNION ALL SELECT '2', 'Deployers', 184549376, 13
    UNION ALL SELECT '2', 'Viewers', 16777217, 14
    UNION ALL SELECT '3', 'Deployers', 16777217, 15
    UNION ALL SELECT '3', 'Deployers', 67108884, 16
    UNION ALL SELECT '3', 'Deployers', 83886088, 17
    UNION ALL SELECT '3', 'Viewers', 16777217, 18
    UNION ALL SELECT '1', 'Deployers', 16777217, 8
    UNION ALL SELECT '1', 'Developers', 16777217, 9
    UNION ALL SELECT '1', 'Testers', 16777217, 10
    UNION ALL SELECT '1', 'Analysts', 16777217, 11
    UNION ALL SELECT '1', 'Analysts', 33554448, 12
    UNION ALL SELECT '1', 'Analysts', 50331664, 13
    UNION ALL SELECT '1', 'Analysts', 67108884, 14
    UNION ALL SELECT '1', 'Analysts', 83886088, 15
    UNION ALL SELECT '1', 'Analysts', 100663328, 16
    UNION ALL SELECT '1', 'Analysts', 201326592, 17
    UNION ALL SELECT '1', 'Analysts', 218103808, 18
    UNION ALL SELECT '2', 'Deployers', 16777217, 15
    UNION ALL SELECT '2', 'Developers', 16777217, 16
    UNION ALL SELECT '2', 'Testers', 16777217, 17
    UNION ALL SELECT '2', 'Analysts', 16777217, 18
    UNION ALL SELECT '3', 'Deployers', 16777217, 19
    UNION ALL SELECT '3', 'Developers', 16777217, 20
    UNION ALL SELECT '3', 'Testers', 16777217, 21
    UNION ALL SELECT '3', 'Analysts', 16777217, 22
) e (root, role_name, mask, ace_order)
JOIN acl_object_identity o ON o.object_id_identity = e.root
JOIN acl_sid s ON s.sid = e.role_name AND s.principal = FALSE;

-- History table of the migration tool of 5.27.15, with the scripts it had applied.
CREATE TABLE "openl_security_flyway" (
    "installed_rank" INTEGER NOT NULL,
    "version" VARCHAR(50),
    "description" VARCHAR(200) NOT NULL,
    "type" VARCHAR(20) NOT NULL,
    "script" VARCHAR(1000) NOT NULL,
    "checksum" INTEGER,
    "installed_by" VARCHAR(100) NOT NULL,
    "installed_on" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "execution_time" INTEGER NOT NULL,
    "success" BOOLEAN NOT NULL,
    CONSTRAINT "openl_security_flyway_pk" PRIMARY KEY ("installed_rank")
);

INSERT INTO "openl_security_flyway" ("installed_rank", "version", "description", "type", "script", "checksum", "installed_by", "execution_time", "success")
SELECT rank, version, description, 'SQL', description, 0, 'openl', 0, TRUE
FROM (
    SELECT 1 AS rank, '1' AS version, 'V1__Base_version.sql' AS description
    UNION ALL SELECT 2, '2', 'V2__Initial_data.sql'
    UNION ALL SELECT 3, '3', 'V3__User_settings.sql'
    UNION ALL SELECT 4, '4', 'V4__Remove_admin.sql'
    UNION ALL SELECT 5, '5', 'V5__tags.sql'
    UNION ALL SELECT 6, '6', 'V6__User_email_and_display_name.sql'
    UNION ALL SELECT 7, '7', 'V7__External_Groups.sql'
    UNION ALL SELECT 8, '8', 'V8__Extend_Group_Name_Length.sql'
    UNION ALL SELECT 9, '9', 'V9__ACL.sql'
    UNION ALL SELECT 10, '10.1', 'V10.1__Replace_privileges_with_permissions.sql'
    UNION ALL SELECT 11, '10.2', 'V10.2__Replace_privileges_with_permissions.sql'
    UNION ALL SELECT 12, '10.3', 'V10.3__Replace_privileges_with_permissions.sql'
    UNION ALL SELECT 13, '11', 'V11__Lock.sql'
    UNION ALL SELECT 14, '12.1', 'V12.1__Expand_nested_groups.sql'
    UNION ALL SELECT 15, '12.2', 'V12.2__Update_ACL_by_expanded_groups.sql'
) applied;
