@setlocal
@set OPENL_VERSION=5.0.6
@set _CP=.;^
lib\org.openl.rules.ruleservice_%OPENL_VERSION%.jar;^
lib\cglib-nodep-2.1_3.jar;^
lib\commons-collections-3.2.jar;^
lib\commons-io-1.3.2.jar;^
lib\commons-lang-2.1.jar;^
lib\commons-logging-1.1.jar;^
lib\concurrent-1.3.4.jar;^
lib\cxf-2.0.3-incubator.jar;^
lib\cxf-manifest-incubator.jar;^
lib\derby-10.2.1.6.jar;^
lib\geronimo-activation_1.1_spec-1.0-M1.jar;^
lib\geronimo-annotation_1.0_spec-1.1.jar;^
lib\geronimo-javamail_1.4_spec-1.0-M1.jar;^
lib\geronimo-jta_1.0.1B_spec-1.0.1.jar;^
lib\geronimo-servlet_2.5_spec-1.1-M1.jar;^
lib\geronimo-ws-metadata_2.0_spec-1.1.1.jar;^
lib\jackrabbit-api-1.3.3.jar;^
lib\jackrabbit-core-1.3.3.jar;^
lib\jackrabbit-jcr-commons-1.3.3.jar;^
lib\jackrabbit-jcr-rmi-1.3.3.jar;^
lib\jackrabbit-text-extractors-1.3.3.jar;^
lib\jaxb-api-2.0.jar;^
lib\jaxb-impl-2.0.5.jar;^
lib\jaxb-xjc-2.0.jar;^
lib\jaxws-api-2.0.jar;^
lib\jcr-1.0.jar;^
lib\jdom-1.0.jar;^
lib\jetty-6.1.5.jar;^
lib\jetty-util-6.1.5.jar;^
lib\junit-3.8.1.jar;^
lib\log4j-1.2.13.jar;^
lib\lucene-core-2.0.0.jar;^
lib\neethi-2.0.2.jar;^
lib\nekohtml-0.9.4.jar;^
lib\org.openl.commons_%OPENL_VERSION%.jar;^
lib\org.openl.core_%OPENL_VERSION%.jar;^
lib\org.openl.j_%OPENL_VERSION%.jar;^
lib\org.openl.rules.helpers_%OPENL_VERSION%.jar;^
lib\org.openl.rules.repository.jcr_%OPENL_VERSION%.jar;^
lib\org.openl.rules.repository_%OPENL_VERSION%.jar;^
lib\org.openl.rules.validator_%OPENL_VERSION%.jar;^
lib\org.openl.rules.workspace_%OPENL_VERSION%.jar;^
lib\org.openl.rules_%OPENL_VERSION%.jar;^
lib\pdfbox-0.6.4.jar;^
lib\poi-2.5.1-final-20040804.jar;^
lib\saaj-api-1.3.jar;^
lib\saaj-impl-1.3.jar;^
lib\slf4j-api-1.3.0.jar;^
lib\slf4j-log4j12-1.3.0.jar;^
lib\stax-api-1.0.1.jar;^
lib\tm-extractors-0.4.jar;^
lib\wsdl4j-1.6.1.jar;^
lib\wstx-asl-3.2.1.jar;^
lib\xbean-2.2.0.jar;^
lib\xercesImpl-2.8.1.jar;^
lib\xml-apis-1.3.02.jar;^
lib\xml-apis-1.3.03.jar;^
lib\xml-resolver-1.2.jar;^
lib\XmlSchema-1.3.2.jar;^
lib\xmlsec-1.3.0.jar
@
start java -classpath "%_CP%" org.openl.rules.ruleservice.RuleServiceMain
@
@endlocal
