package org.openl.studio.config;

import java.util.Locale;
import jakarta.xml.bind.annotation.XmlElement;

import com.fasterxml.classmate.ResolvedType;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.github.victools.jsonschema.generator.CustomDefinition;
import com.github.victools.jsonschema.generator.FieldScope;
import com.github.victools.jsonschema.generator.Option;
import com.github.victools.jsonschema.generator.OptionPreset;
import com.github.victools.jsonschema.generator.SchemaGenerationContext;
import com.github.victools.jsonschema.generator.SchemaGenerator;
import com.github.victools.jsonschema.generator.SchemaGeneratorConfigBuilder;
import com.github.victools.jsonschema.generator.SchemaVersion;
import com.github.victools.jsonschema.module.jackson.JacksonModule;
import com.github.victools.jsonschema.module.swagger2.Swagger2Module;
import org.jspecify.annotations.Nullable;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;
import org.springframework.context.annotation.Scope;

/**
 * Configuration for JSON Schema generation using victools SchemaGenerator.
 * <p>
 * The SchemaGenerator is configured to properly handle classes generated by
 * {@link org.openl.rules.calc.CustomSpreadsheetResultOpenClass} which have
 * getter methods without backing fields.
 * <p>
 * Two generators are offered. {@link #schemaGenerator} describes the values the run, tests and trace APIs
 * publish. {@link #inputSchemaGenerator} describes the input a table takes and also records the defaults a
 * datatype declares, see {@link DeclaredDefaultsAttributeOverride}. A field whose default can be replaced by null
 * accepts null in that schema.
 * <p>
 * Both describe a {@link Locale} as text, the way it is written in JSON and the way the OpenAPI schema of
 * OpenL Rule Services describes it.
 */
@Configuration
public class ObjectSchemaGeneratorConfiguration {

    /**
     * Creates a new SchemaGenerator instance configured for the given ObjectMapper.
     * <p>
     * This is a prototype bean - a new instance is created for each injection/lookup. It is the primary generator.
     * A lookup that names no bean gets this one.
     *
     * @param objectMapper the ObjectMapper to use for introspection
     * @return configured SchemaGenerator
     */
    @Bean
    @Primary
    @Scope("prototype")
    public SchemaGenerator schemaGenerator(ObjectMapper objectMapper) {
        return new SchemaGenerator(configBuilder(objectMapper).build());
    }

    /**
     * Creates a SchemaGenerator for the input a table takes.
     * <p>
     * The schema also carries the defaults a datatype declares as the {@code default} of each property.
     * <p>
     * A field with such a default that is not a primitive accepts {@code null}. A missing field takes the default,
     * so {@code null} is how a caller asks for no value there.
     * <p>
     * This is a prototype bean - a new instance is created for each injection/lookup.
     *
     * @param objectMapper the ObjectMapper to use for introspection and to write the defaults
     * @return configured SchemaGenerator
     */
    @Bean
    @Scope("prototype")
    public SchemaGenerator inputSchemaGenerator(ObjectMapper objectMapper) {
        var configBuilder = configBuilder(objectMapper);
        configBuilder.forTypesInGeneral()
                .withTypeAttributeOverride(new DeclaredDefaultsAttributeOverride(objectMapper));
        configBuilder.forFields()
                .withNullableCheck(ObjectSchemaGeneratorConfiguration::isNillable);
        return new SchemaGenerator(configBuilder.build());
    }

    /**
     * Whether a field can be sent as {@code null} to replace its default.
     * <p>
     * The bean of an OpenL datatype marks such a field as nillable: it declares a default and is not a primitive.
     */
    private static boolean isNillable(FieldScope field) {
        var element = field.getAnnotation(XmlElement.class);
        return element != null && element.nillable();
    }

    private static SchemaGeneratorConfigBuilder configBuilder(ObjectMapper objectMapper) {
        var configBuilder = new SchemaGeneratorConfigBuilder(objectMapper, SchemaVersion.DRAFT_2020_12, OptionPreset.PLAIN_JSON)
                .with(new JacksonModule())
                .with(new Swagger2Module())
                // What a map holds, as the values a key may carry; see MapEntriesAttributeOverride for the
                // maps whose values have no type of their own, and for why a map has to say this at all.
                .with(Option.MAP_VALUES_AS_ADDITIONAL_PROPERTIES);
        configBuilder.forTypesInGeneral()
                .withCustomDefinitionProvider(new JacksonBeanSchemaProvider(objectMapper))
                .withCustomDefinitionProvider(ObjectSchemaGeneratorConfiguration::localeAsText)
                .withTypeAttributeOverride(new MapEntriesAttributeOverride());
        return configBuilder;
    }

    /** Describes a locale as the text it is written as, such as {@code en_US}. Other types are left as they are. */
    private static @Nullable CustomDefinition localeAsText(ResolvedType javaType, SchemaGenerationContext context) {
        if (javaType.getErasedType() != Locale.class) {
            return null;
        }
        return new CustomDefinition(
                context.createStandardDefinition(context.getTypeContext().resolve(String.class), null));
    }
}
