package org.openl.studio.config;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.github.victools.jsonschema.generator.OptionPreset;
import com.github.victools.jsonschema.generator.SchemaGenerator;
import com.github.victools.jsonschema.generator.SchemaGeneratorConfigBuilder;
import com.github.victools.jsonschema.generator.SchemaVersion;
import com.github.victools.jsonschema.module.jackson.JacksonModule;
import com.github.victools.jsonschema.module.swagger2.Swagger2Module;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Scope;

/**
 * Configuration for JSON Schema generation using victools SchemaGenerator.
 * <p>
 * The SchemaGenerator is configured to properly handle classes generated by
 * {@link org.openl.rules.calc.CustomSpreadsheetResultOpenClass} which have
 * getter methods without backing fields.
 */
@Configuration
public class ObjectSchemaGeneratorConfiguration {

    /**
     * Creates a new SchemaGenerator instance configured for the given ObjectMapper.
     * <p>
     * This is a prototype bean - a new instance is created for each injection/lookup.
     *
     * @param objectMapper the ObjectMapper to use for introspection
     * @return configured SchemaGenerator
     */
    @Bean
    @Scope("prototype")
    public SchemaGenerator schemaGenerator(ObjectMapper objectMapper) {
        var configBuilder = new SchemaGeneratorConfigBuilder(objectMapper, SchemaVersion.DRAFT_2020_12, OptionPreset.PLAIN_JSON)
                .with(new JacksonModule())
                .with(new Swagger2Module());
        configBuilder.forTypesInGeneral()
                .withCustomDefinitionProvider(new JacksonBeanSchemaProvider(objectMapper));
        return new SchemaGenerator(configBuilder.build());
    }
}
