/* BExGrammarTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. BExGrammarTokenManager.java */
package org.openl.grammar.bexgrammar;

/** Token Manager. */
public class BExGrammarTokenManager implements BExGrammarConstants {
  // CommonTokenAction: use the begins/ends fields added to the Jack
  // CharStream class to set corresponding fields in each Token (which was
  // also extended with new fields). By default Jack doesn't supply absolute
  // offsets, just line/column offsets
  void CommonTokenAction(Token t)
  {
  //    t.beginsAt = input_stream.beginOffset;
  //    t.endsAt = input_stream.endOffset;
  //    throw new RuntimeException("Define CommonTokenAction");
  /*
    org.openl.util.Log.debug(
      "Token = <"
        + t.image
        + "> "
        + "("
        + t.beginLine
        + ","
        + t.beginColumn
        + ")-("
        + t.endLine
        + ","
        + t.endColumn
        + ")"
        + " "
        + t.kind
        + " = "
        + JGrammarConstants.tokenImage[t.kind]);
*/

  }

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1, long active2){
   switch (pos)
   {
      case 0:
         if ((active0 & 0x1ffffffffc0L) != 0L || (active1 & 0x3f800000000L) != 0L || (active2 & 0x7d6f6dffcL) != 0L)
         {
            jjmatchedKind = 120;
            return 105;
         }
         if ((active0 & 0xe000000000000L) != 0L)
            return 1;
         if ((active1 & 0x2000000002004000L) != 0L)
            return 99;
         return -1;
      case 1:
         if ((active1 & 0x2000000000000000L) != 0L)
            return 97;
         if ((active0 & 0x1b7ffbeff80L) != 0L || (active1 & 0x3f800000000L) != 0L || (active2 & 0x5d406c004L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 1;
            }
            return 105;
         }
         if ((active0 & 0x4800410040L) != 0L || (active2 & 0x200b01ff8L) != 0L)
            return 105;
         return -1;
      case 2:
         if ((active0 & 0x1a6feaefe00L) != 0L || (active1 & 0x3f800000000L) != 0L || (active2 & 0x1d4b6c014L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 2;
            }
            return 105;
         }
         if ((active0 & 0x1101100180L) != 0L || (active2 & 0x400000000L) != 0L)
            return 105;
         return -1;
      case 3:
         if ((active0 & 0x247c8cf600L) != 0L || (active1 & 0x3f800000000L) != 0L || (active2 & 0x154b6c014L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 3;
            }
            return 105;
         }
         if ((active0 & 0x18282220800L) != 0L || (active2 & 0x80000000L) != 0L)
            return 105;
         return -1;
      case 4:
         if ((active2 & 0x100000010L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x1488c400L) != 0L || (active1 & 0x3f800000000L) != 0L || (active2 & 0x54b6c004L) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 4;
            }
            return 105;
         }
         if ((active0 & 0x2468043200L) != 0L)
            return 105;
         return -1;
      case 5:
         if ((active2 & 0x4b00000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active2 & 0x100000010L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x88c400L) != 0L || (active1 & 0x3f800000000L) != 0L || (active2 & 0x5006c004L) != 0L)
         {
            jjmatchedKind = 120;
            jjmatchedPos = 5;
            return 105;
         }
         if ((active0 & 0x54000000L) != 0L)
            return 105;
         return -1;
      case 6:
         if ((active1 & 0x18000000000L) != 0L || (active2 & 0x6c004L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active2 & 0x4b00000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active2 & 0x100000010L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x804400L) != 0L || (active2 & 0x50000000L) != 0L)
         {
            if (jjmatchedPos != 6)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 6;
            }
            return 105;
         }
         if ((active0 & 0x88000L) != 0L)
            return 105;
         return -1;
      case 7:
         if ((active1 & 0x18000000000L) != 0L || (active2 & 0x6c004L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active2 & 0x4b00000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active2 & 0x100000010L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x800400L) != 0L || (active2 & 0x50000000L) != 0L)
         {
            jjmatchedKind = 120;
            jjmatchedPos = 7;
            return 105;
         }
         if ((active0 & 0x4000L) != 0L)
            return 105;
         return -1;
      case 8:
         if ((active2 & 0x6c004L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active2 & 0xa00000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active2 & 0x100000010L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x800000L) != 0L || (active2 & 0x50000000L) != 0L)
         {
            jjmatchedKind = 120;
            jjmatchedPos = 8;
            return 105;
         }
         if ((active0 & 0x400L) != 0L)
            return 105;
         return -1;
      case 9:
         if ((active2 & 0x50000000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active2 & 0x6c000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active2 & 0xa00000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active2 & 0x10L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x800000L) != 0L)
            return 105;
         return -1;
      case 10:
         if ((active2 & 0x50000000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active2 & 0x6c000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active2 & 0xa00000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active2 & 0x10L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 3;
            }
            return -1;
         }
         return -1;
      case 11:
         if ((active2 & 0x50000000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active2 & 0x6c000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active2 & 0xa00000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active2 & 0x10L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 3;
            }
            return -1;
         }
         return -1;
      case 12:
         if ((active2 & 0x40000000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active2 & 0x6c000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active2 & 0xa00000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active2 & 0x10L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 3;
            }
            return -1;
         }
         return -1;
      case 13:
         if ((active2 & 0x40000000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active2 & 0x6c000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active2 & 0xa00000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active2 & 0x10L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 3;
            }
            return -1;
         }
         return -1;
      case 14:
         if ((active2 & 0x40000000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active2 & 0x6c000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active2 & 0xa00000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active2 & 0x10L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 3;
            }
            return -1;
         }
         return -1;
      case 15:
         if ((active2 & 0x40000000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active2 & 0x6c000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active2 & 0xa00000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active2 & 0x10L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 3;
            }
            return -1;
         }
         return -1;
      case 16:
         if ((active2 & 0x40000000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active2 & 0x64000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active2 & 0xa00000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active2 & 0x10L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 3;
            }
            return -1;
         }
         return -1;
      case 17:
         if ((active2 & 0x40000000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active2 & 0x60000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active2 & 0xa00000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 120;
               jjmatchedPos = 4;
            }
            return -1;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1, long active2){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1, active2), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 58;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x50L, 0x10000L);
      case 37:
         jjmatchedKind = 82;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x20000000L, 0x0L);
      case 38:
         jjmatchedKind = 79;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4000100L, 0x0L);
      case 40:
         return jjStopAtPos(0, 41);
      case 41:
         return jjStopAtPos(0, 42);
      case 42:
         jjmatchedKind = 77;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x201000000L, 0x28000000L);
      case 43:
         jjmatchedKind = 75;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x400200L, 0x0L);
      case 44:
         return jjStopAtPos(0, 48);
      case 45:
         jjmatchedKind = 76;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x400800400L, 0x0L);
      case 46:
         jjmatchedKind = 49;
         return jjMoveStringLiteralDfa1_0(0xc000000000000L, 0x0L, 0x0L);
      case 47:
         jjmatchedKind = 78;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2000000002000000L, 0x0L);
      case 58:
         return jjStopAtPos(0, 61);
      case 59:
         return jjStopAtPos(0, 47);
      case 60:
         jjmatchedKind = 56;
         return jjMoveStringLiteralDfa1_0(0x200000000000000L, 0x40080023L, 0x0L);
      case 61:
         jjmatchedKind = 53;
         return jjMoveStringLiteralDfa1_0(0xc000000000000000L, 0x0L, 0x0L);
      case 62:
         jjmatchedKind = 54;
         return jjMoveStringLiteralDfa1_0(0x80000000000000L, 0x18030000cL, 0x0L);
      case 63:
         return jjStopAtPos(0, 60);
      case 64:
         return jjStopAtPos(0, 141);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x400L, 0x0L, 0x0L);
      case 91:
         return jjStopAtPos(0, 45);
      case 93:
         return jjStopAtPos(0, 46);
      case 94:
         jjmatchedKind = 81;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x10000000L, 0x80000L);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x80L, 0x0L, 0x400000000L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x200L, 0x0L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x7800L, 0x0L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x18000L, 0x0L, 0x10L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x20000L, 0x0L, 0x4L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x1c0000L, 0x0L, 0x0L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x200000L, 0x0L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x4000c00000L, 0x0L, 0x1fe8L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x8000000000L, 0x0L, 0x80000000L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x100000000L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x3000100L, 0x0L, 0x0L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x800000040L, 0x0L, 0x200b00000L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x4000000L, 0x0L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x18000000L, 0x3f800000000L, 0x606c000L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x111e0000000L, 0x0L, 0x50000000L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x200000000L, 0x0L, 0x400000L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x2400000000L, 0x0L, 0x0L);
      case 123:
         return jjStopAtPos(0, 43);
      case 124:
         jjmatchedKind = 80;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8000080L, 0x0L);
      case 125:
         return jjStopAtPos(0, 44);
      case 126:
         jjmatchedKind = 59;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x1000000L);
      case 8230:
         return jjStopAtPos(0, 52);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1, long active2){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1, active2);
      return 1;
   }
   switch(curChar)
   {
      case 33:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0L, active2, 0x20000000L);
      case 38:
         if ((active1 & 0x100L) != 0L)
            return jjStopAtPos(1, 72);
         break;
      case 42:
         if ((active1 & 0x200000000L) != 0L)
            return jjStopAtPos(1, 97);
         else if ((active1 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 125, 97);
         break;
      case 43:
         if ((active1 & 0x200L) != 0L)
            return jjStopAtPos(1, 73);
         break;
      case 45:
         if ((active1 & 0x400L) != 0L)
            return jjStopAtPos(1, 74);
         break;
      case 46:
         if ((active0 & 0x4000000000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000000000L, active1, 0L, active2, 0L);
      case 60:
         if ((active1 & 0x80000L) != 0L)
         {
            jjmatchedKind = 83;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x40000000L, active2, 0L);
      case 61:
         if ((active0 & 0x4000000000000000L) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x1L) != 0L)
         {
            jjmatchedKind = 64;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x4L) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x10L) != 0L)
         {
            jjmatchedKind = 68;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x400000L) != 0L)
            return jjStopAtPos(1, 86);
         else if ((active1 & 0x800000L) != 0L)
            return jjStopAtPos(1, 87);
         else if ((active1 & 0x1000000L) != 0L)
            return jjStopAtPos(1, 88);
         else if ((active1 & 0x2000000L) != 0L)
            return jjStopAtPos(1, 89);
         else if ((active1 & 0x4000000L) != 0L)
            return jjStopAtPos(1, 90);
         else if ((active1 & 0x8000000L) != 0L)
            return jjStopAtPos(1, 91);
         else if ((active1 & 0x10000000L) != 0L)
            return jjStopAtPos(1, 92);
         else if ((active1 & 0x20000000L) != 0L)
            return jjStopAtPos(1, 93);
         return jjMoveStringLiteralDfa2_0(active0, 0x8280000000000000L, active1, 0x4aL, active2, 0L);
      case 62:
         if ((active1 & 0x20L) != 0L)
            return jjStopAtPos(1, 69);
         else if ((active1 & 0x100000L) != 0L)
         {
            jjmatchedKind = 84;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x400000000L) != 0L)
            return jjStopAtPos(1, 98);
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x180200000L, active2, 0L);
      case 64:
         if ((active2 & 0x10000L) != 0L)
            return jjStopAtPos(1, 144);
         else if ((active2 & 0x80000L) != 0L)
            return jjStopAtPos(1, 147);
         else if ((active2 & 0x400000L) != 0L)
            return jjStopAtPos(1, 150);
         else if ((active2 & 0x1000000L) != 0L)
            return jjStopAtPos(1, 152);
         else if ((active2 & 0x2000000L) != 0L)
            return jjStopAtPos(1, 153);
         else if ((active2 & 0x8000000L) != 0L)
            return jjStopAtPos(1, 155);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x41c00L, active1, 0L, active2, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x8005008000L, active1, 0L, active2, 0x8006c000L);
      case 102:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(1, 22, 105);
         else if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(1, 35, 105);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x13460000000L, active1, 0L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000L, active1, 0L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000L, active1, 0L, active2, 0L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x800080L, active1, 0L, active2, 0x400000000L);
      case 111:
         if ((active0 & 0x10000L) != 0L)
         {
            jjmatchedKind = 16;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x200306100L, active1, 0L, active2, 0x100000010L);
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0L, active2, 0x4000000L);
      case 113:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0L, active2, 0x4L);
      case 114:
         if ((active0 & 0x40L) != 0L)
         {
            jjmatchedKind = 6;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x180000200L, active1, 0L, active2, 0x250b00000L);
      case 115:
         if ((active0 & 0x4000000000L) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0L, active2, 0x1fe8L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x3f800000000L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0xa000000L, active1, 0L, active2, 0L);
      case 119:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000L, active1, 0L, active2, 0L);
      case 124:
         if ((active1 & 0x80L) != 0L)
            return jjStopAtPos(1, 71);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1, active2);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(0, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1, active2);
      return 2;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0L, active2, 0x200001fe8L);
      case 46:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStopAtPos(2, 51);
         break;
      case 61:
         if ((active0 & 0x80000000000000L) != 0L)
         {
            jjmatchedKind = 55;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x200000000000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x40000000L) != 0L)
            return jjStopAtPos(2, 94);
         else if ((active1 & 0x80000000L) != 0L)
            return jjStopAtPos(2, 95);
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000000000L, active1, 0x4aL, active2, 0L);
      case 62:
         if ((active1 & 0x200000L) != 0L)
         {
            jjmatchedKind = 85;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x100000000L, active2, 0L);
      case 64:
         if ((active2 & 0x20000000L) != 0L)
            return jjStopAtPos(2, 157);
         break;
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000000L, active1, 0L, active2, 0x50000000L);
      case 100:
         if ((active0 & 0x80L) != 0L)
         {
            jjmatchedKind = 7;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0L, active2, 0x400b00000L);
      case 101:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 36, 105);
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000200L, active1, 0L, active2, 0x10L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000L, active1, 0L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x610000000L, active1, 0L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x2040400L, active1, 0L, active2, 0x406c000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x86000L, active1, 0L, active2, 0L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000L, active1, 0L, active2, 0L);
      case 114:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(2, 20, 105);
         return jjMoveStringLiteralDfa3_0(active0, 0x60000000L, active1, 0x3f800000000L, active2, 0x100000000L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000820800L, active1, 0L, active2, 0x80000000L);
      case 116:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(2, 8, 105);
         return jjMoveStringLiteralDfa3_0(active0, 0x4201000L, active1, 0L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000L, active1, 0L, active2, 0x4L);
      case 119:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(2, 24, 105);
         break;
      case 121:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(2, 32, 105);
         break;
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1, active2);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(1, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1, active2);
      return 3;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0L, active2, 0x400000000L);
      case 61:
         if ((active0 & 0x8000000000000000L) != 0L)
            return jjStopAtPos(3, 63);
         else if ((active1 & 0x2L) != 0L)
            return jjStopAtPos(3, 65);
         else if ((active1 & 0x8L) != 0L)
            return jjStopAtPos(3, 67);
         else if ((active1 & 0x40L) != 0L)
            return jjStopAtPos(3, 70);
         else if ((active1 & 0x100000000L) != 0L)
            return jjStopAtPos(3, 96);
         break;
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x88200L, active1, 0L, active2, 0x4L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x1400L, active1, 0L, active2, 0L);
      case 100:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(3, 33, 105);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0L, active2, 0x20L);
      case 101:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(3, 11, 105);
         else if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(3, 17, 105);
         else if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(3, 31, 105);
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000L, active1, 0L, active2, 0x100b6c000L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x3f800000000L, active2, 0x4000400L);
      case 108:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(3, 25, 105);
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000L, active1, 0L, active2, 0x200000140L);
      case 109:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0L, active2, 0x880L);
      case 110:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 40, 105);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0L, active2, 0x50001200L);
      case 111:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(3, 21, 105);
         return jjMoveStringLiteralDfa4_0(active0, 0x60000000L, active1, 0L, active2, 0L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000000L, active1, 0L, active2, 0L);
      case 115:
         if ((active0 & 0x8000000000L) != 0L)
         {
            jjmatchedKind = 39;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x42000L, active1, 0L, active2, 0x80000018L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x10804000L, active1, 0L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000L, active1, 0L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1, active2);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(2, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1, active2);
      return 4;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0L, active2, 0x180000010L);
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000L, active1, 0L, active2, 0x8L);
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000L, active1, 0L, active2, 0x6c000L);
      case 101:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(4, 18, 105);
         else if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(4, 34, 105);
         else if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 37, 105);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0L, active2, 0x200000140L);
      case 104:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(4, 12, 105);
         break;
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000L, active1, 0L, active2, 0x20L);
      case 107:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(4, 9, 105);
         break;
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000L, active1, 0L, active2, 0x4L);
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0L, active2, 0x400000000L);
      case 110:
         if ((active2 & 0x400L) != 0L)
            return jjStopAtPos(4, 138);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x3f800000000L, active2, 0L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0L, active2, 0x1a80L);
      case 114:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(4, 27, 105);
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000L, active1, 0L, active2, 0xb00000L);
      case 115:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0L, active2, 0x50000000L);
      case 116:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(4, 13, 105);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0L, active2, 0x4000000L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x8400L, active1, 0L, active2, 0L);
      case 119:
         if ((active0 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 29;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000L, active1, 0L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1, active2);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(3, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1, active2);
      return 5;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0L, active2, 0x4b01200L);
      case 102:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0L, active2, 0x50000020L);
      case 103:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x3f800000000L, active2, 0L);
      case 104:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(5, 28, 105);
         break;
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x88400L, active1, 0L, active2, 0L);
      case 109:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0L, active2, 0x8L);
      case 110:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(5, 26, 105);
         return jjMoveStringLiteralDfa6_0(active0, 0x804000L, active1, 0L, active2, 0x10L);
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0L, active2, 0x400000000L);
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0L, active2, 0x880L);
      case 115:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(5, 30, 105);
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0L, active2, 0x200000144L);
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0L, active2, 0x18006c000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1, active2);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(4, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1, active2);
      return 6;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0L, active2, 0x6c004L);
      case 33:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x10000000000L, active2, 0L);
      case 60:
         if ((active1 & 0x1000000000L) != 0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x20800000000L, active2, 0L);
      case 61:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x8000000000L, active2, 0L);
      case 62:
         if ((active1 & 0x4000000000L) != 0L)
         {
            jjmatchedKind = 102;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x2000000000L, active2, 0L);
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x400L, active1, 0L, active2, 0L);
      case 98:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0L, active2, 0x4100000L);
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000L, active1, 0L, active2, 0L);
      case 100:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0L, active2, 0x800000L);
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0L, active2, 0x888L);
      case 102:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0L, active2, 0x20L);
      case 104:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0L, active2, 0x180000000L);
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0L, active2, 0x200000L);
      case 108:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0L, active2, 0x1000L);
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0L, active2, 0x200L);
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0L, active2, 0x50000010L);
      case 114:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0L, active2, 0x400000000L);
      case 115:
         if ((active2 & 0x200000000L) != 0L)
            return jjStopAtPos(6, 161);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0L, active2, 0x140L);
      case 116:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(6, 15, 105);
         break;
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x4000L, active1, 0L, active2, 0L);
      case 121:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(6, 19, 105);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1, active2);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(5, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1, active2);
      return 7;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0L, active2, 0x9c8L);
      case 61:
         if ((active1 & 0x800000000L) != 0L)
            return jjStopAtPos(7, 99);
         else if ((active1 & 0x2000000000L) != 0L)
            return jjStopAtPos(7, 101);
         else if ((active1 & 0x8000000000L) != 0L)
            return jjStopAtPos(7, 103);
         else if ((active1 & 0x10000000000L) != 0L)
            return jjStopAtPos(7, 104);
         break;
      case 62:
         if ((active1 & 0x20000000000L) != 0L)
            return jjStopAtPos(7, 105);
         break;
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0L, active2, 0x18000c000L);
      case 101:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(7, 14, 105);
         else if ((active2 & 0x400000000L) != 0L)
            return jjStopAtPos(7, 162);
         return jjMoveStringLiteralDfa8_0(active0, 0x800000L, active1, 0L, active2, 0x801020L);
      case 102:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0L, active2, 0x60000L);
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0L, active2, 0x200000L);
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0L, active2, 0x200L);
      case 114:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0L, active2, 0x50000000L);
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0x400L, active1, 0L, active2, 0x14L);
      case 121:
         if ((active2 & 0x100000L) != 0L)
            return jjStopAtPos(7, 148);
         else if ((active2 & 0x4000000L) != 0L)
            return jjStopAtPos(7, 154);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1, active2);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(6, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, 0L, active2);
      return 8;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active2, 0x10L);
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active2, 0x8L);
      case 99:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active2, 0xa00000L);
      case 101:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(8, 10, 105);
         break;
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active2, 0x60000L);
      case 108:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active2, 0xc000L);
      case 109:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active2, 0x50000000L);
      case 110:
         if ((active2 & 0x80000000L) != 0L)
            return jjStopAtPos(8, 159);
         else if ((active2 & 0x100000000L) != 0L)
            return jjStopAtPos(8, 160);
         break;
      case 111:
         if ((active2 & 0x4L) != 0L)
            return jjStopAtPos(8, 130);
         return jjMoveStringLiteralDfa9_0(active0, 0x800000L, active2, 0x900L);
      case 114:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active2, 0x220L);
      case 115:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active2, 0x1000L);
      case 116:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active2, 0xc0L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, 0L, active2);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0, long old2, long active2){
   if (((active0 &= old0) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(7, old0, 0L, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, 0L, active2);
      return 9;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active2, 0x50000000L);
      case 101:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active2, 0x230L);
      case 102:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(9, 23, 105);
         break;
      case 104:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active2, 0xc0L);
      case 108:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active2, 0xc000L);
      case 114:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active2, 0xa60900L);
      case 115:
         if ((active2 & 0x8L) != 0L)
            return jjStopAtPos(9, 131);
         return jjMoveStringLiteralDfa10_0(active0, 0L, active2, 0x1000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0, 0L, active2);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0, long old2, long active2){
   if (((active0 &= old0) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(8, old0, 0L, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, 0L, 0L, active2);
      return 10;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa11_0(active2, 0xdb00L);
      case 97:
         return jjMoveStringLiteralDfa11_0(active2, 0xc0L);
      case 101:
         return jjMoveStringLiteralDfa11_0(active2, 0xa00000L);
      case 110:
         return jjMoveStringLiteralDfa11_0(active2, 0x20L);
      case 113:
         return jjMoveStringLiteralDfa11_0(active2, 0x10L);
      case 115:
         return jjMoveStringLiteralDfa11_0(active2, 0x60000L);
      case 116:
         return jjMoveStringLiteralDfa11_0(active2, 0x10000000L);
      case 117:
         return jjMoveStringLiteralDfa11_0(active2, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(9, 0L, 0L, active2);
}
private int jjMoveStringLiteralDfa11_0(long old2, long active2){
   if (((active2 &= old2)) == 0L)
      return jjStartNfa_0(9, 0L, 0L, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, 0L, 0L, active2);
      return 11;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa12_0(active2, 0xa00000L);
      case 101:
         return jjMoveStringLiteralDfa12_0(active2, 0x900L);
      case 104:
         return jjMoveStringLiteralDfa12_0(active2, 0x4000L);
      case 110:
         if ((active2 & 0x40L) != 0L)
            return jjStopAtPos(11, 134);
         else if ((active2 & 0x80L) != 0L)
            return jjStopAtPos(11, 135);
         return jjMoveStringLiteralDfa12_0(active2, 0x40000000L);
      case 111:
         if ((active2 & 0x10000000L) != 0L)
            return jjStopAtPos(11, 156);
         break;
      case 116:
         return jjMoveStringLiteralDfa12_0(active2, 0x61220L);
      case 117:
         return jjMoveStringLiteralDfa12_0(active2, 0x10L);
      case 119:
         return jjMoveStringLiteralDfa12_0(active2, 0x8000L);
      default :
         break;
   }
   return jjStartNfa_0(10, 0L, 0L, active2);
}
private int jjMoveStringLiteralDfa12_0(long old2, long active2){
   if (((active2 &= old2)) == 0L)
      return jjStartNfa_0(10, 0L, 0L, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, 0L, 0L, active2);
      return 12;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa13_0(active2, 0x60020L);
      case 97:
         return jjMoveStringLiteralDfa13_0(active2, 0x4010L);
      case 104:
         return jjMoveStringLiteralDfa13_0(active2, 0x9200L);
      case 105:
         return jjMoveStringLiteralDfa13_0(active2, 0x40000000L);
      case 113:
         return jjMoveStringLiteralDfa13_0(active2, 0x900L);
      case 115:
         return jjMoveStringLiteralDfa13_0(active2, 0xa00000L);
      default :
         break;
   }
   return jjStartNfa_0(11, 0L, 0L, active2);
}
private int jjMoveStringLiteralDfa13_0(long old2, long active2){
   if (((active2 &= old2)) == 0L)
      return jjStartNfa_0(11, 0L, 0L, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, 0L, 0L, active2);
      return 13;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa14_0(active2, 0x1200L);
      case 101:
         return jjMoveStringLiteralDfa14_0(active2, 0x8000L);
      case 102:
         return jjMoveStringLiteralDfa14_0(active2, 0x20L);
      case 104:
         return jjMoveStringLiteralDfa14_0(active2, 0x20000L);
      case 105:
         return jjMoveStringLiteralDfa14_0(active2, 0xa00000L);
      case 108:
         return jjMoveStringLiteralDfa14_0(active2, 0x10L);
      case 113:
         return jjMoveStringLiteralDfa14_0(active2, 0x40000000L);
      case 117:
         return jjMoveStringLiteralDfa14_0(active2, 0x900L);
      case 118:
         return jjMoveStringLiteralDfa14_0(active2, 0x4000L);
      case 119:
         return jjMoveStringLiteralDfa14_0(active2, 0x40000L);
      default :
         break;
   }
   return jjStartNfa_0(12, 0L, 0L, active2);
}
private int jjMoveStringLiteralDfa14_0(long old2, long active2){
   if (((active2 &= old2)) == 0L)
      return jjStartNfa_0(12, 0L, 0L, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, 0L, 0L, active2);
      return 14;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa15_0(active2, 0x10L);
      case 97:
         return jjMoveStringLiteralDfa15_0(active2, 0x20900L);
      case 104:
         return jjMoveStringLiteralDfa15_0(active2, 0x40000L);
      case 105:
         return jjMoveStringLiteralDfa15_0(active2, 0x4000L);
      case 110:
         if ((active2 & 0x200L) != 0L)
            return jjStopAtPos(14, 137);
         else if ((active2 & 0x1000L) != 0L)
            return jjStopAtPos(14, 140);
         return jjMoveStringLiteralDfa15_0(active2, 0xa00000L);
      case 114:
         return jjMoveStringLiteralDfa15_0(active2, 0x8020L);
      case 117:
         return jjMoveStringLiteralDfa15_0(active2, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(13, 0L, 0L, active2);
}
private int jjMoveStringLiteralDfa15_0(long old2, long active2){
   if (((active2 &= old2)) == 0L)
      return jjStartNfa_0(13, 0L, 0L, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, 0L, 0L, active2);
      return 15;
   }
   switch(curChar)
   {
      case 101:
         if ((active2 & 0x8000L) != 0L)
            return jjStopAtPos(15, 143);
         return jjMoveStringLiteralDfa16_0(active2, 0x40040000L);
      case 103:
         return jjMoveStringLiteralDfa16_0(active2, 0xa00000L);
      case 108:
         if ((active2 & 0x100L) != 0L)
            return jjStopAtPos(15, 136);
         else if ((active2 & 0x800L) != 0L)
            return jjStopAtPos(15, 139);
         break;
      case 110:
         return jjMoveStringLiteralDfa16_0(active2, 0x4000L);
      case 111:
         return jjMoveStringLiteralDfa16_0(active2, 0x20L);
      case 116:
         return jjMoveStringLiteralDfa16_0(active2, 0x10L);
      case 118:
         return jjMoveStringLiteralDfa16_0(active2, 0x20000L);
      default :
         break;
   }
   return jjStartNfa_0(14, 0L, 0L, active2);
}
private int jjMoveStringLiteralDfa16_0(long old2, long active2){
   if (((active2 &= old2)) == 0L)
      return jjStartNfa_0(14, 0L, 0L, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, 0L, 0L, active2);
      return 16;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa17_0(active2, 0x40a00000L);
      case 103:
         if ((active2 & 0x4000L) != 0L)
            return jjStopAtPos(16, 142);
         break;
      case 105:
         return jjMoveStringLiteralDfa17_0(active2, 0x20000L);
      case 109:
         if ((active2 & 0x20L) != 0L)
            return jjStopAtPos(16, 133);
         break;
      case 111:
         if ((active2 & 0x10L) != 0L)
            return jjStopAtPos(16, 132);
         break;
      case 114:
         return jjMoveStringLiteralDfa17_0(active2, 0x40000L);
      default :
         break;
   }
   return jjStartNfa_0(15, 0L, 0L, active2);
}
private int jjMoveStringLiteralDfa17_0(long old2, long active2){
   if (((active2 &= old2)) == 0L)
      return jjStartNfa_0(15, 0L, 0L, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(16, 0L, 0L, active2);
      return 17;
   }
   switch(curChar)
   {
      case 98:
         return jjMoveStringLiteralDfa18_0(active2, 0xa00000L);
      case 101:
         if ((active2 & 0x40000L) != 0L)
            return jjStopAtPos(17, 146);
         break;
      case 110:
         return jjMoveStringLiteralDfa18_0(active2, 0x20000L);
      case 116:
         return jjMoveStringLiteralDfa18_0(active2, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(16, 0L, 0L, active2);
}
private int jjMoveStringLiteralDfa18_0(long old2, long active2){
   if (((active2 &= old2)) == 0L)
      return jjStartNfa_0(16, 0L, 0L, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(17, 0L, 0L, active2);
      return 18;
   }
   switch(curChar)
   {
      case 103:
         if ((active2 & 0x20000L) != 0L)
            return jjStopAtPos(18, 145);
         break;
      case 111:
         if ((active2 & 0x40000000L) != 0L)
            return jjStopAtPos(18, 158);
         break;
      case 121:
         if ((active2 & 0x200000L) != 0L)
            return jjStopAtPos(18, 149);
         else if ((active2 & 0x800000L) != 0L)
            return jjStopAtPos(18, 151);
         break;
      default :
         break;
   }
   return jjStartNfa_0(17, 0L, 0L, active2);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec3 = {
   0x1ff00000fffffffeL, 0xffffffffffffc000L, 0xffffffffL, 0x600000000000000L
};
static final long[] jjbitVec4 = {
   0x0L, 0x0L, 0x0L, 0xff7fffffff7fffffL
};
static final long[] jjbitVec5 = {
   0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec6 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffL, 0x0L
};
static final long[] jjbitVec7 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0x0L, 0x0L
};
static final long[] jjbitVec8 = {
   0x3fffffffffffL, 0x0L, 0x0L, 0x0L
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 105;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 99:
                  if (curChar == 47)
                  {
                     if (kind > 126)
                        kind = 126;
                     { jjCheckNAddStates(0, 2); }
                  }
                  else if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 113)
                        kind = 113;
                     { jjCheckNAddStates(3, 17); }
                  }
                  else if (curChar == 47)
                     { jjAddStates(18, 19); }
                  else if (curChar == 36)
                  {
                     if (kind > 120)
                        kind = 120;
                     { jjCheckNAddStates(20, 22); }
                  }
                  else if (curChar == 34)
                     { jjCheckNAddStates(23, 25); }
                  else if (curChar == 39)
                     { jjAddStates(26, 27); }
                  else if (curChar == 46)
                     { jjCheckNAdd(1); }
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 106)
                        kind = 106;
                     { jjCheckNAddStates(28, 31); }
                  }
                  else if (curChar == 48)
                  {
                     if (kind > 106)
                        kind = 106;
                     { jjCheckNAddStates(32, 34); }
                  }
                  else if (curChar == 36)
                     { jjCheckNAddTwoStates(30, 34); }
                  break;
               case 105:
                  if ((0x3ff001000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(92, 93); }
                  else if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 94;
                  if ((0x3ff001000000000L & l) != 0L)
                  {
                     if (kind > 120)
                        kind = 120;
                     { jjCheckNAdd(91); }
                  }
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 112)
                     kind = 112;
                  { jjCheckNAddStates(35, 37); }
                  break;
               case 3:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(4); }
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 112)
                     kind = 112;
                  { jjCheckNAddTwoStates(4, 5); }
                  break;
               case 6:
                  if (curChar == 39)
                     { jjAddStates(26, 27); }
                  break;
               case 7:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     { jjCheckNAdd(8); }
                  break;
               case 8:
                  if (curChar == 39 && kind > 118)
                     kind = 118;
                  break;
               case 10:
                  if ((0x8400000000L & l) != 0L)
                     { jjCheckNAdd(8); }
                  break;
               case 11:
                  if ((0xff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(12, 8); }
                  break;
               case 12:
                  if ((0xff000000000000L & l) != 0L)
                     { jjCheckNAdd(8); }
                  break;
               case 13:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 14:
                  if ((0xff000000000000L & l) != 0L)
                     { jjCheckNAdd(12); }
                  break;
               case 15:
                  if (curChar == 34)
                     { jjCheckNAddStates(23, 25); }
                  break;
               case 16:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     { jjCheckNAddStates(23, 25); }
                  break;
               case 18:
                  if ((0x8400000000L & l) != 0L)
                     { jjCheckNAddStates(23, 25); }
                  break;
               case 19:
                  if (curChar == 34 && kind > 119)
                     kind = 119;
                  break;
               case 20:
                  if ((0xff000000000000L & l) != 0L)
                     { jjCheckNAddStates(38, 41); }
                  break;
               case 21:
                  if ((0xff000000000000L & l) != 0L)
                     { jjCheckNAddStates(23, 25); }
                  break;
               case 22:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 23:
                  if ((0xff000000000000L & l) != 0L)
                     { jjCheckNAdd(21); }
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 26:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 27:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 28:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(23, 25); }
                  break;
               case 29:
                  if (curChar == 36)
                     { jjCheckNAddTwoStates(30, 34); }
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 113)
                     kind = 113;
                  { jjCheckNAddStates(42, 44); }
                  break;
               case 31:
                  if (curChar == 46)
                     { jjCheckNAdd(32); }
                  break;
               case 32:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 113)
                     kind = 113;
                  { jjCheckNAddTwoStates(32, 33); }
                  break;
               case 34:
                  if ((0x3fe000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(35, 41); }
                  break;
               case 35:
                  if (curChar == 44)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 36:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 37:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 38:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 113)
                     kind = 113;
                  { jjCheckNAddStates(45, 47); }
                  break;
               case 39:
                  if (curChar == 46)
                     { jjCheckNAdd(40); }
                  break;
               case 40:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 113)
                     kind = 113;
                  { jjCheckNAddTwoStates(40, 33); }
                  break;
               case 41:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(42, 35); }
                  break;
               case 42:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(35); }
                  break;
               case 43:
                  if (curChar != 48)
                     break;
                  if (kind > 106)
                     kind = 106;
                  { jjCheckNAddStates(32, 34); }
                  break;
               case 45:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 106)
                     kind = 106;
                  { jjCheckNAddTwoStates(45, 46); }
                  break;
               case 47:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 106)
                     kind = 106;
                  { jjCheckNAddTwoStates(47, 46); }
                  break;
               case 48:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 106)
                     kind = 106;
                  { jjCheckNAddStates(28, 31); }
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 106)
                     kind = 106;
                  { jjCheckNAddTwoStates(49, 46); }
                  break;
               case 50:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 113)
                     kind = 113;
                  { jjCheckNAddStates(3, 17); }
                  break;
               case 51:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(51, 52); }
                  break;
               case 52:
                  if (curChar != 46)
                     break;
                  if (kind > 112)
                     kind = 112;
                  { jjCheckNAddStates(48, 50); }
                  break;
               case 53:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 112)
                     kind = 112;
                  { jjCheckNAddStates(48, 50); }
                  break;
               case 55:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(56); }
                  break;
               case 56:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 112)
                     kind = 112;
                  { jjCheckNAddTwoStates(56, 5); }
                  break;
               case 57:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(57, 58); }
                  break;
               case 59:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(60); }
                  break;
               case 60:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 112)
                     kind = 112;
                  { jjCheckNAddTwoStates(60, 5); }
                  break;
               case 61:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(51, 53); }
                  break;
               case 63:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(64); }
                  break;
               case 64:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(64, 5); }
                  break;
               case 65:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 66:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 67:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 68:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 69:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 70:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 71:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 72:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 73:
                  if ((0x3ff000000000000L & l) != 0L && kind > 114)
                     kind = 114;
                  break;
               case 74:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 75:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 76:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 77:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 115)
                     kind = 115;
                  jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 78:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 79:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 80:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 115)
                     kind = 115;
                  jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 81:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 82:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 83:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 84:
                  if ((0x3ff000000000000L & l) != 0L && kind > 115)
                     kind = 115;
                  break;
               case 85:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(54, 56); }
                  break;
               case 86:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 87:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 88:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(89); }
                  break;
               case 89:
                  if (curChar == 37 && kind > 116)
                     kind = 116;
                  break;
               case 90:
                  if (curChar != 36)
                     break;
                  if (kind > 120)
                     kind = 120;
                  { jjCheckNAddStates(20, 22); }
                  break;
               case 91:
                  if ((0x3ff001000000000L & l) == 0L)
                     break;
                  if (kind > 120)
                     kind = 120;
                  { jjCheckNAdd(91); }
                  break;
               case 92:
                  if ((0x3ff001000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(92, 93); }
                  break;
               case 93:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 94:
                  if (curChar != 36)
                     break;
                  if (kind > 123)
                     kind = 123;
                  { jjCheckNAdd(95); }
                  break;
               case 95:
                  if ((0x3ff001000000000L & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  { jjCheckNAdd(95); }
                  break;
               case 96:
                  if (curChar == 47)
                     { jjAddStates(18, 19); }
                  break;
               case 97:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 98:
                  if ((0xffff7fffffffffffL & l) != 0L && kind > 124)
                     kind = 124;
                  break;
               case 100:
                  if (curChar != 47)
                     break;
                  if (kind > 126)
                     kind = 126;
                  { jjCheckNAddStates(0, 2); }
                  break;
               case 101:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 126)
                     kind = 126;
                  { jjCheckNAddStates(0, 2); }
                  break;
               case 102:
                  if ((0x2400L & l) != 0L && kind > 126)
                     kind = 126;
                  break;
               case 103:
                  if (curChar == 10 && kind > 126)
                     kind = 126;
                  break;
               case 104:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 120)
                     kind = 120;
                  { jjCheckNAddStates(20, 22); }
                  break;
               case 105:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(92, 93); }
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 120)
                        kind = 120;
                     { jjCheckNAdd(91); }
                  }
                  break;
               case 2:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(57, 58); }
                  break;
               case 5:
                  if ((0x5000000050L & l) != 0L && kind > 112)
                     kind = 112;
                  break;
               case 7:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAdd(8); }
                  break;
               case 9:
                  if (curChar == 92)
                     { jjAddStates(59, 61); }
                  break;
               case 10:
                  if ((0x14404410000000L & l) != 0L)
                     { jjCheckNAdd(8); }
                  break;
               case 16:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(23, 25); }
                  break;
               case 17:
                  if (curChar == 92)
                     { jjAddStates(62, 65); }
                  break;
               case 18:
                  if ((0x14404410000000L & l) != 0L)
                     { jjCheckNAddStates(23, 25); }
                  break;
               case 24:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 25:
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 26:
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 27:
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 28:
                  if ((0x7e00000000L & l) != 0L)
                     { jjCheckNAddStates(23, 25); }
                  break;
               case 33:
                  if ((0x2804L & l) != 0L && kind > 113)
                     kind = 113;
                  break;
               case 44:
                  if ((0x100000001000000L & l) != 0L)
                     { jjCheckNAdd(45); }
                  break;
               case 45:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 106)
                     kind = 106;
                  { jjCheckNAddTwoStates(45, 46); }
                  break;
               case 46:
                  if ((0x100000001000L & l) != 0L && kind > 106)
                     kind = 106;
                  break;
               case 54:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(66, 67); }
                  break;
               case 58:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(68, 69); }
                  break;
               case 62:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(70, 71); }
                  break;
               case 91:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 120)
                     kind = 120;
                  { jjCheckNAdd(91); }
                  break;
               case 92:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(92, 93); }
                  break;
               case 94:
               case 95:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 123)
                     kind = 123;
                  { jjCheckNAdd(95); }
                  break;
               case 98:
                  if (kind > 124)
                     kind = 124;
                  break;
               case 101:
                  if (kind > 126)
                     kind = 126;
                  { jjAddStates(0, 2); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 120)
                     kind = 120;
                  { jjCheckNAddStates(20, 22); }
                  break;
               case 105:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 120)
                        kind = 120;
                     { jjCheckNAdd(91); }
                  }
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddTwoStates(92, 93); }
                  break;
               case 7:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 16:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjAddStates(23, 25); }
                  break;
               case 91:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 120)
                     kind = 120;
                  { jjCheckNAdd(91); }
                  break;
               case 92:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddTwoStates(92, 93); }
                  break;
               case 94:
               case 95:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 123)
                     kind = 123;
                  { jjCheckNAdd(95); }
                  break;
               case 98:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 124)
                     kind = 124;
                  break;
               case 101:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 126)
                     kind = 126;
                  { jjAddStates(0, 2); }
                  break;
               default : if (i1 == 0 || l1 == 0 || i2 == 0 ||  l2 == 0) break; else break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 105 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
private int jjMoveStringLiteralDfa0_2(){
   switch(curChar)
   {
      case 42:
         return jjMoveStringLiteralDfa1_2(0x1L);
      default :
         return 1;
   }
}
private int jjMoveStringLiteralDfa1_2(long active2){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 47:
         if ((active2 & 0x1L) != 0L)
            return jjStopAtPos(1, 128);
         break;
      default :
         return 2;
   }
   return 2;
}
private int jjMoveStringLiteralDfa0_1(){
   switch(curChar)
   {
      case 42:
         return jjMoveStringLiteralDfa1_1(0x8000000000000000L);
      default :
         return 1;
   }
}
private int jjMoveStringLiteralDfa1_1(long active1){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 47:
         if ((active1 & 0x8000000000000000L) != 0L)
            return jjStopAtPos(1, 127);
         break;
      default :
         return 2;
   }
   return 2;
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, "\157\162", "\141\156\144", "\156\157\164", 
"\142\162\145\141\153", "\103\141\154\143\165\154\141\164\145", "\143\141\163\145", 
"\143\141\164\143\150", "\143\157\156\163\164", "\143\157\156\164\151\156\165\145", 
"\144\145\146\141\165\154\164", "\144\157", "\145\154\163\145", "\146\141\154\163\145", 
"\146\151\156\141\154\154\171", "\146\157\162", "\147\157\164\157", "\151\146", 
"\151\156\163\164\141\156\143\145\157\146", "\156\145\167", "\156\165\154\154", "\162\145\164\165\162\156", 
"\163\165\160\145\162", "\163\167\151\164\143\150", "\164\150\162\157\167", 
"\164\150\162\157\167\163", "\164\162\165\145", "\164\162\171", "\166\157\151\144", 
"\167\150\151\154\145", "\157\146", "\164\150\145", "\167\150\145\162\145", "\151\163", 
"\154\145\163\163", "\164\150\141\156", "\50", "\51", "\173", "\175", "\133", "\135", "\73", 
"\54", "\56", "\56\56", "\56\56\56", "\u2026", "\75", "\76", "\76\75\75", "\74", 
"\74\75\75", "\41", "\176", "\77", "\72", "\75\75", "\75\75\75\75", "\74\75", 
"\74\75\75\75", "\76\75", "\76\75\75\75", "\41\75", "\74\76", "\41\75\75\75", "\174\174", 
"\46\46", "\53\53", "\55\55", "\53", "\55", "\52", "\57", "\46", "\174", "\136", "\45", 
"\74\74", "\76\76", "\76\76\76", "\53\75", "\55\75", "\52\75", "\57\75", "\46\75", 
"\174\75", "\136\75", "\45\75", "\74\74\75", "\76\76\75", "\76\76\76\75", "\52\52", 
"\55\76", "\163\164\162\151\156\147\74\75", "\163\164\162\151\156\147\74", 
"\163\164\162\151\156\147\76\75", "\163\164\162\151\156\147\76", "\163\164\162\151\156\147\75\75", 
"\163\164\162\151\156\147\41\75", "\163\164\162\151\156\147\74\76", null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, "\145\161\165\141\154\163\40\164\157", 
"\151\163\40\163\141\155\145\40\141\163", "\144\157\145\163\40\156\157\164\40\145\161\165\141\154\40\164\157", 
"\151\163\40\144\151\146\146\145\162\145\156\164\40\146\162\157\155", "\151\163\40\154\145\163\163\40\164\150\141\156", 
"\151\163\40\155\157\162\145\40\164\150\141\156", "\151\163\40\154\145\163\163\40\157\162\40\145\161\165\141\154", 
"\151\163\40\156\157\40\155\157\162\145\40\164\150\141\156", "\151\163\40\151\156", 
"\151\163\40\155\157\162\145\40\157\162\40\145\161\165\141\154", "\151\163\40\156\157\40\154\145\163\163\40\164\150\141\156", "\100", 
"\163\145\154\145\143\164\40\141\154\154\40\150\141\166\151\156\147", "\163\145\154\145\143\164\40\141\154\154\40\167\150\145\162\145", "\41\100", 
"\163\145\154\145\143\164\40\146\151\162\163\164\40\150\141\166\151\156\147", "\163\145\154\145\143\164\40\146\151\162\163\164\40\167\150\145\162\145", 
"\136\100", "\157\162\144\145\162\40\142\171", 
"\157\162\144\145\162\40\151\156\143\162\145\141\163\151\156\147\40\142\171", "\166\100", 
"\157\162\144\145\162\40\144\145\143\162\145\141\163\151\156\147\40\142\171", "\176\100", "\163\100", "\163\160\154\151\164\40\142\171", "\52\100", 
"\164\162\141\156\163\146\157\162\155\40\164\157", "\52\41\100", 
"\164\162\141\156\163\146\157\162\155\40\165\156\151\161\165\145\40\164\157", "\154\145\163\163\40\164\150\141\156", "\155\157\162\145\40\164\150\141\156", 
"\157\162\40\154\145\163\163", "\141\156\144\40\155\157\162\145", };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   t.image = curTokenImage;

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   101, 102, 104, 51, 52, 57, 58, 61, 62, 5, 30, 31, 33, 65, 74, 85, 
   86, 89, 99, 100, 91, 92, 93, 16, 17, 19, 7, 9, 49, 46, 35, 41, 
   44, 47, 46, 1, 2, 5, 16, 17, 21, 19, 30, 31, 33, 35, 39, 33, 
   53, 54, 5, 61, 62, 5, 85, 86, 89, 3, 4, 10, 11, 13, 18, 20, 
   22, 24, 55, 56, 59, 60, 63, 64, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default :
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}
private static final boolean jjCanMove_1(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec4[i2] & l2) != 0L);
      case 48:
         return ((jjbitVec5[i2] & l2) != 0L);
      case 49:
         return ((jjbitVec6[i2] & l2) != 0L);
      case 51:
         return ((jjbitVec7[i2] & l2) != 0L);
      case 61:
         return ((jjbitVec8[i2] & l2) != 0L);
      default :
         if ((jjbitVec3[i1] & l1) != 0L)
            return true;
         return false;
   }
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      CommonTokenAction(matchedToken);
      return matchedToken;
   }
   image = jjimage;
   image.setLength(0);
   jjimageLen = 0;

   for (;;)
   {
     switch(curLexState)
     {
       case 0:
         try { input_stream.backup(0);
            while (curChar <= 32 && (0x100003600L & (1L << curChar)) != 0L)
               curChar = input_stream.BeginToken();
         }
         catch (java.io.IOException e1) { continue EOFLoop; }
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_0();
         break;
       case 1:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_1();
         if (jjmatchedPos == 0 && jjmatchedKind > 129)
         {
            jjmatchedKind = 129;
         }
         break;
       case 2:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_2();
         if (jjmatchedPos == 0 && jjmatchedKind > 129)
         {
            jjmatchedKind = 129;
         }
         break;
     }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
           matchedToken.specialToken = specialToken;
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           CommonTokenAction(matchedToken);
           return matchedToken;
        }
        else if ((jjtoSkip[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
           {
              matchedToken = jjFillToken();
              if (specialToken == null)
                 specialToken = matchedToken;
              else
              {
                 matchedToken.specialToken = specialToken;
                 specialToken = (specialToken.next = matchedToken);
              }
              SkipLexicalActions(matchedToken);
           }
           else
              SkipLexicalActions(null);
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
        MoreLexicalActions();
      if (jjnewLexState[jjmatchedKind] != -1)
        curLexState = jjnewLexState[jjmatchedKind];
        curPos = 0;
        jjmatchedKind = 0x7fffffff;
        try {
           curChar = input_stream.readChar();
           continue;
        }
        catch (java.io.IOException e1) { }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
   }
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      case 124 :
         image.append(input_stream.GetSuffix(jjimageLen));
         jjimageLen = 0;
    input_stream.backup(1);
         break;
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public BExGrammarTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public BExGrammarTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 105; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 3 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
   "IN_FORMAL_COMMENT",
   "IN_MULTI_LINE_COMMENT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 
   2, -1, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xffffffffffffffc1L, 0x9df07ffffffffffL, 0x7fffffffcL, 
};
static final long[] jjtoSkip = {
   0x3eL, 0xc000000000000000L, 0x1L, 
};
static final long[] jjtoSpecial = {
   0x0L, 0xc000000000000000L, 0x1L, 
};
static final long[] jjtoMore = {
   0x0L, 0x3000000000000000L, 0x2L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[105];
    private final int[] jjstateSet = new int[2 * 105];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
