/* Generated By:JavaCC: Do not edit this line. BExGrammarConstants.java */
package org.openl.grammar.bexgrammar;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BExGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int _WHITESPACE = 6;
  /** RegularExpression Id. */
  int DOT_OPERATOR = 7;
  /** RegularExpression Id. */
  int BREAK = 8;
  /** RegularExpression Id. */
  int CASE = 9;
  /** RegularExpression Id. */
  int CATCH = 10;
  /** RegularExpression Id. */
  int CONST = 11;
  /** RegularExpression Id. */
  int CONTINUE = 12;
  /** RegularExpression Id. */
  int _DEFAULT = 13;
  /** RegularExpression Id. */
  int DO = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int FALSE = 16;
  /** RegularExpression Id. */
  int FINALLY = 17;
  /** RegularExpression Id. */
  int FOR = 18;
  /** RegularExpression Id. */
  int GOTO = 19;
  /** RegularExpression Id. */
  int IF = 20;
  /** RegularExpression Id. */
  int INSTANCEOF = 21;
  /** RegularExpression Id. */
  int NEW = 22;
  /** RegularExpression Id. */
  int NULL = 23;
  /** RegularExpression Id. */
  int RETURN = 24;
  /** RegularExpression Id. */
  int SUPER = 25;
  /** RegularExpression Id. */
  int THROW = 26;
  /** RegularExpression Id. */
  int THROWS = 27;
  /** RegularExpression Id. */
  int TRUE = 28;
  /** RegularExpression Id. */
  int TRY = 29;
  /** RegularExpression Id. */
  int VOID = 30;
  /** RegularExpression Id. */
  int WHILE = 31;
  /** RegularExpression Id. */
  int OF_THE = 32;
  /** RegularExpression Id. */
  int LPAREN = 33;
  /** RegularExpression Id. */
  int RPAREN = 34;
  /** RegularExpression Id. */
  int LBRACE = 35;
  /** RegularExpression Id. */
  int RBRACE = 36;
  /** RegularExpression Id. */
  int LBRACKET = 37;
  /** RegularExpression Id. */
  int RBRACKET = 38;
  /** RegularExpression Id. */
  int SEMICOLON = 39;
  /** RegularExpression Id. */
  int COMMA = 40;
  /** RegularExpression Id. */
  int DDOT = 41;
  /** RegularExpression Id. */
  int TDOT = 42;
  /** RegularExpression Id. */
  int TDOT_UNICODE = 43;
  /** RegularExpression Id. */
  int WHERE = 44;
  /** RegularExpression Id. */
  int EQ = 45;
  /** RegularExpression Id. */
  int EQUALS_TO = 46;
  /** RegularExpression Id. */
  int IS_SAME_AS = 47;
  /** RegularExpression Id. */
  int IS_THE_SAME_AS = 48;
  /** RegularExpression Id. */
  int ASSIGN = 49;
  /** RegularExpression Id. */
  int GT = 50;
  /** RegularExpression Id. */
  int STRICT_GT = 51;
  /** RegularExpression Id. */
  int LT = 52;
  /** RegularExpression Id. */
  int STRICT_LT = 53;
  /** RegularExpression Id. */
  int NOT = 54;
  /** RegularExpression Id. */
  int TILDE = 55;
  /** RegularExpression Id. */
  int HOOK = 56;
  /** RegularExpression Id. */
  int COLON = 57;
  /** RegularExpression Id. */
  int STRICT_EQ = 58;
  /** RegularExpression Id. */
  int LE = 59;
  /** RegularExpression Id. */
  int STRICT_LE = 60;
  /** RegularExpression Id. */
  int GE = 61;
  /** RegularExpression Id. */
  int STRICT_GE = 62;
  /** RegularExpression Id. */
  int NE = 63;
  /** RegularExpression Id. */
  int NE_ALT = 64;
  /** RegularExpression Id. */
  int STRICT_NE = 65;
  /** RegularExpression Id. */
  int BOOL_OR = 66;
  /** RegularExpression Id. */
  int BOOL_AND = 67;
  /** RegularExpression Id. */
  int INCR = 68;
  /** RegularExpression Id. */
  int DECR = 69;
  /** RegularExpression Id. */
  int PLUS = 70;
  /** RegularExpression Id. */
  int MINUS = 71;
  /** RegularExpression Id. */
  int STAR = 72;
  /** RegularExpression Id. */
  int SLASH = 73;
  /** RegularExpression Id. */
  int BIT_AND = 74;
  /** RegularExpression Id. */
  int BIT_OR = 75;
  /** RegularExpression Id. */
  int BIT_XOR = 76;
  /** RegularExpression Id. */
  int REM = 77;
  /** RegularExpression Id. */
  int LSHIFT = 78;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 79;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 80;
  /** RegularExpression Id. */
  int PLUSASSIGN = 81;
  /** RegularExpression Id. */
  int MINUSASSIGN = 82;
  /** RegularExpression Id. */
  int STARASSIGN = 83;
  /** RegularExpression Id. */
  int SLASHASSIGN = 84;
  /** RegularExpression Id. */
  int ANDASSIGN = 85;
  /** RegularExpression Id. */
  int ORASSIGN = 86;
  /** RegularExpression Id. */
  int XORASSIGN = 87;
  /** RegularExpression Id. */
  int REMASSIGN = 88;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 89;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 90;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 91;
  /** RegularExpression Id. */
  int EXP = 92;
  /** RegularExpression Id. */
  int IMPL = 93;
  /** RegularExpression Id. */
  int STRING_LE = 94;
  /** RegularExpression Id. */
  int STRING_LT = 95;
  /** RegularExpression Id. */
  int STRING_GE = 96;
  /** RegularExpression Id. */
  int STRING_GT = 97;
  /** RegularExpression Id. */
  int STRING_EQ = 98;
  /** RegularExpression Id. */
  int STRING_NE = 99;
  /** RegularExpression Id. */
  int STRING_NE_ALT = 100;
  /** RegularExpression Id. */
  int DOES_NOT_EQUAL_TO = 101;
  /** RegularExpression Id. */
  int IS_DIFFERENT_FROM = 102;
  /** RegularExpression Id. */
  int IS_LESS_THAN = 103;
  /** RegularExpression Id. */
  int IS_MORE_THAN = 104;
  /** RegularExpression Id. */
  int IS_LESS_OR_EQUAL = 105;
  /** RegularExpression Id. */
  int IS_NO_MORE_THAN = 106;
  /** RegularExpression Id. */
  int IS_IN = 107;
  /** RegularExpression Id. */
  int IS_MORE_OR_EQUAL = 108;
  /** RegularExpression Id. */
  int IS_NO_LESS_THAN = 109;
  /** RegularExpression Id. */
  int SELECT_ALL_HAVING = 110;
  /** RegularExpression Id. */
  int SELECT_ALL_WHERE = 111;
  /** RegularExpression Id. */
  int SELECT_FIRST_HAVING = 112;
  /** RegularExpression Id. */
  int SELECT_FIRST_WHERE = 113;
  /** RegularExpression Id. */
  int ORDER_BY = 114;
  /** RegularExpression Id. */
  int ORDER_INCREASING_BY = 115;
  /** RegularExpression Id. */
  int ORDER_DECREASING_BY = 116;
  /** RegularExpression Id. */
  int SPLIT_BY = 117;
  /** RegularExpression Id. */
  int TRANSFORM_TO = 118;
  /** RegularExpression Id. */
  int TRANSFORM_UNIQUE_TO = 119;
  /** RegularExpression Id. */
  int LESS_THAN = 120;
  /** RegularExpression Id. */
  int MORE_THAN = 121;
  /** RegularExpression Id. */
  int OR_LESS = 122;
  /** RegularExpression Id. */
  int AND_MORE = 123;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 124;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 125;
  /** RegularExpression Id. */
  int HEX_LITERAL = 126;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 127;
  /** RegularExpression Id. */
  int FP_LITERAL1 = 128;
  /** RegularExpression Id. */
  int FP_LITERAL2 = 129;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 130;
  /** RegularExpression Id. */
  int BUSINESS_INTEGER_LITERAL = 131;
  /** RegularExpression Id. */
  int DATE_FORMAT_LITERAL_4_2_2 = 132;
  /** RegularExpression Id. */
  int TIME_FORMAT_LITERAL = 133;
  /** RegularExpression Id. */
  int PERCENT_LITERAL = 134;
  /** RegularExpression Id. */
  int EXPONENT = 135;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 136;
  /** RegularExpression Id. */
  int STRING_LITERAL = 137;
  /** RegularExpression Id. */
  int IDENTIFIER = 138;
  /** RegularExpression Id. */
  int LETTER = 139;
  /** RegularExpression Id. */
  int DIGIT = 140;
  /** RegularExpression Id. */
  int RANGE_VARIABLE = 141;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 144;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 145;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 146;

  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 0;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 1;
  /** Lexical state. */
  int REF_IDENTIFIER = 2;
  /** Lexical state. */
  int DEFAULT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "<_WHITESPACE>",
    "\".\"",
    "\"break\"",
    "\"case\"",
    "\"catch\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"else\"",
    "\"false\"",
    "\"finally\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"instanceof\"",
    "\"new\"",
    "\"null\"",
    "\"return\"",
    "\"super\"",
    "\"throw\"",
    "\"throws\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"while\"",
    "<OF_THE>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\"..\"",
    "\"...\"",
    "\"\\u2026\"",
    "\"where\"",
    "<EQ>",
    "<EQUALS_TO>",
    "<IS_SAME_AS>",
    "<IS_THE_SAME_AS>",
    "\"=\"",
    "\">\"",
    "\">==\"",
    "\"<\"",
    "\"<==\"",
    "<NOT>",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"====\"",
    "\"<=\"",
    "\"<===\"",
    "\">=\"",
    "\">===\"",
    "\"!=\"",
    "\"<>\"",
    "\"!===\"",
    "<BOOL_OR>",
    "<BOOL_AND>",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"**\"",
    "\"->\"",
    "\"string<=\"",
    "\"string<\"",
    "\"string>=\"",
    "\"string>\"",
    "\"string==\"",
    "\"string!=\"",
    "\"string<>\"",
    "<DOES_NOT_EQUAL_TO>",
    "<IS_DIFFERENT_FROM>",
    "<IS_LESS_THAN>",
    "<IS_MORE_THAN>",
    "<IS_LESS_OR_EQUAL>",
    "<IS_NO_MORE_THAN>",
    "<IS_IN>",
    "<IS_MORE_OR_EQUAL>",
    "<IS_NO_LESS_THAN>",
    "<SELECT_ALL_HAVING>",
    "<SELECT_ALL_WHERE>",
    "<SELECT_FIRST_HAVING>",
    "<SELECT_FIRST_WHERE>",
    "<ORDER_BY>",
    "<ORDER_INCREASING_BY>",
    "<ORDER_DECREASING_BY>",
    "<SPLIT_BY>",
    "<TRANSFORM_TO>",
    "<TRANSFORM_UNIQUE_TO>",
    "<LESS_THAN>",
    "<MORE_THAN>",
    "<OR_LESS>",
    "<AND_MORE>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FP_LITERAL1>",
    "<FP_LITERAL2>",
    "<FLOATING_POINT_LITERAL>",
    "<BUSINESS_INTEGER_LITERAL>",
    "<DATE_FORMAT_LITERAL_4_2_2>",
    "<TIME_FORMAT_LITERAL>",
    "<PERCENT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<RANGE_VARIABLE>",
    "<token of kind 142>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 147>",
    "\"@\"",
    "\"!@\"",
    "\"^@\"",
    "\"v@\"",
    "\"~@\"",
    "\"s@\"",
    "\"*@\"",
    "\"*!@\"",
  };

}
