import React from 'react'
import { CONFIG } from '../services'

// RapiDoc is a custom element: importing it defines <rapi-doc>. It is bundled into this screen's own chunk,
// so it is fetched when a reader opens the documentation and never before.
import 'rapidoc'

declare module 'react' {
    namespace JSX {
        interface IntrinsicElements {
            'rapi-doc': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & {
                'render-style'?: string
                'show-header'?: string
                'show-method-in-nav-bar'?: string
                'sort-endpoints-by'?: string
                'spec-url'?: string
            }
        }
    }
}

/**
 * The documentation of the REST API the application itself is built on.
 *
 * <p>The specification is generated by the server and read from it, so the page always describes the running
 * version. The server is the one the page is served from, so a request tried out from here is sent with the
 * session the reader already has.
 *
 * <p>It is a page of its own, drawn without the application's header, and the renderer keeps the colours and
 * the settings it was read in before — its own dark palette, the endpoints of one tag at a time, sorted by
 * path.
 */
export const ApiDocs: React.FC = () => (
    <rapi-doc
        data-testid="api-docs"
        render-style="focused"
        show-header="false"
        show-method-in-nav-bar="as-colored-text"
        sort-endpoints-by="path"
        spec-url={`${CONFIG.API_ROOT}/openapi.json`}
        style={{ height: '100vh', width: '100%' }}
    />
)
