package org.openl.rules.ruleservice.kafka.publish;

public interface KafkaHeaders {
    String METHOD_NAME = "METHOD_NAME";
    String METHOD_PARAMETERS = "METHOD_PARAMETERS";
    String CORRELATION_ID = "CORRELATION_ID";
    String REPLY_PARTITION = "REPLY_PARTITION";
    String REPLY_TOPIC = "REPLY_TOPIC";
    String REPLY_DLT_PARTITION = "REPLY_DLT_PARTITION";
    String REPLY_DLT_TOPIC = "REPLY_DLT_TOPIC";

    String DLT_EXCEPTION_FQCN = "DLT_EXCEPTION_FQCN";
    String DLT_EXCEPTION_MESSAGE = "DLT_EXCEPTION_MESSAGE";
    String DLT_EXCEPTION_STACKTRACE = "DLT_EXCEPTION_STACKTRACE";
    String DLT_ORIGINAL_OFFSET = "DLT_ORIGINAL_OFFSET";
    String DLT_ORIGINAL_PARTITION = "DLT_ORIGINAL_PARTITION";
    String DLT_ORIGINAL_TOPIC = "DLT_ORIGINAL_TOPIC";
    String DLT_ORIGINAL_MESSAGE_KEY = "DLT_ORIGINAL_MESSAGE_KEY";
}
