CREATE TABLE ACL_PERMISSION_MAPPING (
    MASK ${bigint} not null,
    AUTHORITY ${varchar}(50) not null,
    PRIMARY KEY (AUTHORITY, MASK)
);

INSERT INTO ACL_PERMISSION_MAPPING (MASK, AUTHORITY) VALUES (16777217, 'VIEW_PROJECTS');        /*READ*/
INSERT INTO ACL_PERMISSION_MAPPING (MASK, AUTHORITY) VALUES (16777217, 'EDIT_PROJECTS');        /*READ*/
INSERT INTO ACL_PERMISSION_MAPPING (MASK, AUTHORITY) VALUES (33554448, 'CREATE_PROJECTS');      /*CREATE_PROJECTS*/
INSERT INTO ACL_PERMISSION_MAPPING (MASK, AUTHORITY) VALUES (50331664, 'EDIT_PROJECTS');        /*APPEND*/
INSERT INTO ACL_PERMISSION_MAPPING (MASK, AUTHORITY) VALUES (67108892, 'EDIT_PROJECTS');        /*EDIT*/
INSERT INTO ACL_PERMISSION_MAPPING (MASK, AUTHORITY) VALUES (83886084, 'DELETE_PROJECTS');      /*ARCHIVE*/
INSERT INTO ACL_PERMISSION_MAPPING (MASK, AUTHORITY) VALUES (100663304, 'ERASE_PROJECTS');      /*DELETE*/
INSERT INTO ACL_PERMISSION_MAPPING (MASK, AUTHORITY) VALUES (201326592, 'RUN');                 /* RUN */
INSERT INTO ACL_PERMISSION_MAPPING (MASK, AUTHORITY) VALUES (201326592, 'TRACE');               /* RUN */
INSERT INTO ACL_PERMISSION_MAPPING (MASK, AUTHORITY) VALUES (218103808, 'BENCHMARK');           /* BENCHMARK */
INSERT INTO ACL_PERMISSION_MAPPING (MASK, AUTHORITY) VALUES (234881024, 'CREATE_TABLES');       /* CREATE_TABLES */
INSERT INTO ACL_PERMISSION_MAPPING (MASK, AUTHORITY) VALUES (251658240, 'EDIT_TABLES');         /* EDIT_TABLES */
INSERT INTO ACL_PERMISSION_MAPPING (MASK, AUTHORITY) VALUES (268435456, 'REMOVE_TABLES');       /* DELETE_TABLES */
INSERT INTO ACL_PERMISSION_MAPPING (MASK, AUTHORITY) VALUES (184549376, 'DEPLOY_PROJECTS');     /* DEPLOY_PROJECT */
INSERT INTO ACL_PERMISSION_MAPPING (MASK, AUTHORITY) VALUES (117440528, 'CREATE_DEPLOYMENT');   /* CREATE_DEPLOYMENT */
INSERT INTO ACL_PERMISSION_MAPPING (MASK, AUTHORITY) VALUES (134217732, 'EDIT_DEPLOYMENT');     /* EDIT_DEPLOYMENT */
INSERT INTO ACL_PERMISSION_MAPPING (MASK, AUTHORITY) VALUES (150994948, 'DELETE_DEPLOYMENT');   /* ARCHIVE_DEPLOYMENT */
INSERT INTO ACL_PERMISSION_MAPPING (MASK, AUTHORITY) VALUES (167772168, 'ERASE_DEPLOYMENT');    /* DELETE_DEPLOYMENT */

INSERT INTO ACL_SID (PRINCIPAL, SID) VALUES (false, 'Administrators');
INSERT INTO ACL_SID (PRINCIPAL, SID) VALUES (true, 'admin');
INSERT INTO ACL_SID (PRINCIPAL, SID) SELECT DISTINCT false, t2.GROUPNAME FROM OpenL_Group_Authorities t1 INNER JOIN OpenL_Groups t2 ON t1.GROUPID = t2.ID WHERE AUTHORITY in (SELECT apm.AUTHORITY FROM ACL_PERMISSION_MAPPING AS apm);

INSERT INTO ACL_CLASS (CLASS, CLASS_ID_TYPE) VALUES ('org.openl.security.acl.repository.ProjectArtifact', 'java.lang.String');
INSERT INTO ACL_CLASS (CLASS, CLASS_ID_TYPE) VALUES ('org.openl.security.acl.repository.Root', 'java.lang.String');

INSERT INTO ACL_OBJECT_IDENTITY (OBJECT_ID_CLASS, OBJECT_ID_IDENTITY, PARENT_OBJECT, OWNER_SID, ENTRIES_INHERITING)
SELECT a.ID, '1', null, c.ID, true
FROM ACL_CLASS a,
     ACL_SID c
WHERE a.CLASS = 'org.openl.security.acl.repository.Root'
  AND a.CLASS_ID_TYPE = 'java.lang.String'
  AND c.PRINCIPAL = false
  AND c.SID = 'Administrators';

INSERT INTO ACL_OBJECT_IDENTITY (OBJECT_ID_CLASS, OBJECT_ID_IDENTITY, PARENT_OBJECT, OWNER_SID, ENTRIES_INHERITING)
SELECT a.ID, 'design', b.ID, c.ID, true
FROM ACL_CLASS a,
     ACL_OBJECT_IDENTITY b,
     ACL_SID c
WHERE a.CLASS = 'org.openl.security.acl.repository.ProjectArtifact'
  AND a.CLASS_ID_TYPE = 'java.lang.String'
  AND b.OBJECT_ID_IDENTITY = '1'
  AND c.PRINCIPAL = false
  AND c.SID = 'Administrators';

CREATE SEQUENCE ACE_ENTRY_ROW_NUM_1;
ALTER SEQUENCE ACE_ENTRY_ROW_NUM_1 RESTART WITH 1;

INSERT INTO ACL_ENTRY (ACL_OBJECT_IDENTITY, SID, MASK, GRANTING, AUDIT_SUCCESS, AUDIT_FAILURE, ACE_ORDER)
    SELECT b.ID, a.ID, c.MASK, true, false, false, (SELECT count(*) FROM ACL_ENTRY d WHERE b.ID = d.ACL_OBJECT_IDENTITY) + nextval('ACE_ENTRY_ROW_NUM_1') - 1
    FROM ACL_SID a,
         ACL_OBJECT_IDENTITY b,
         ACL_PERMISSION_MAPPING c,
         (SELECT DISTINCT t2.GROUPNAME AS GROUPNAME, t1.AUTHORITY AS AUTHORITY
                    FROM OpenL_Group_Authorities t1
                             INNER JOIN OpenL_Groups t2 ON t1.GROUPID = t2.ID
                    WHERE t1.AUTHORITY IN (SELECT apm.AUTHORITY FROM ACL_PERMISSION_MAPPING AS apm)) AS d
    WHERE b.OBJECT_ID_IDENTITY = '1'
      AND a.PRINCIPAL = false
      AND c.AUTHORITY = d.AUTHORITY
      AND a.SID = d.GROUPNAME;

DELETE FROM OpenL_Group_Authorities WHERE AUTHORITY IN (SELECT apm.AUTHORITY FROM ACL_PERMISSION_MAPPING AS apm WHERE apm.AUTHORITY <> 'VIEW_PROJECTS');

DROP SEQUENCE ACE_ENTRY_ROW_NUM_1;
DROP TABLE ACL_PERMISSION_MAPPING;