ALTER TABLE OpenLUser CHANGE COLUMN Privileges UserPrivileges LONGTEXT NULL DEFAULT NULL;

ALTER TABLE UserGroup CHANGE COLUMN Privileges UserPrivileges LONGTEXT NULL DEFAULT NULL;

UPDATE UserGroup g
SET g.UserPrivileges = CONCAT(g.UserPrivileges, ',PRIVILEGE_UNLOCK_PROJECTS,PRIVILEGE_UNLOCK_DEPLOYMENT')
WHERE g.UserPrivileges LIKE '%PRIVILEGE_ADMINISTRATE%';