/**
 * Names of the codes the fields of the runtime context take.
 *
 * The schema of the context lists the codes only. The names are those of the OpenL enumerations the context
 * declares, and are kept here so the form needs no request to show them.
 */
export const RUNTIME_CONTEXT_LABELS: Record<string, Record<string, string>> = {
    usState: {
        AL: 'Alabama',
        AK: 'Alaska',
        AS: 'American Samoa',
        AZ: 'Arizona',
        AR: 'Arkansas',
        CA: 'California',
        CO: 'Colorado',
        CT: 'Connecticut',
        DC: 'District of Columbia',
        DE: 'Delaware',
        FL: 'Florida',
        GA: 'Georgia',
        GU: 'Guam',
        HI: 'Hawaii',
        ID: 'Idaho',
        IL: 'Illinois',
        IN: 'Indiana',
        IA: 'Iowa',
        KS: 'Kansas',
        KY: 'Kentucky',
        LA: 'Louisiana',
        ME: 'Maine',
        MD: 'Maryland',
        MA: 'Massuchusets',
        MI: 'Michigan',
        MN: 'Minnesota',
        MS: 'Mississipi',
        MO: 'Missouri',
        MT: 'Montana',
        NE: 'Nebraska',
        NV: 'Nevada',
        NH: 'New Hampshire',
        NJ: 'New Jersey',
        NM: 'New Mexico',
        NY: 'New York',
        NC: 'North California',
        ND: 'North Dakota',
        MP: 'Northern Mariana Islands',
        OH: 'Ohio',
        OK: 'Oklahoma',
        OR: 'Oregon',
        PA: 'Pennsylvania',
        PR: 'Puerto Rico',
        RI: 'Rhode Island',
        SC: 'South California',
        SD: 'South Dakota',
        TN: 'Tennessee',
        TX: 'Texas',
        UT: 'Utah',
        VT: 'Vermont',
        VI: 'Virgin Islands',
        VA: 'Virginia',
        WA: 'Washington',
        WV: 'West Virginia',
        WI: 'Wisconsin',
        WY: 'Wyoming',
    },
    country: {
        AE: 'United Arab Emirates',
        AL: 'Albania',
        AR: 'Argentina',
        AS: 'American Samoa',
        AT: 'Austria',
        AU: 'Australia',
        BA: 'Bosnia And Herzegowina',
        BB: 'Barbados',
        BE: 'Belgium',
        BG: 'Bulgaria',
        BH: 'Bahrain',
        BO: 'Bolivia',
        BR: 'Brazil',
        BY: 'Belarus',
        CA: 'Canada',
        CH: 'Switzerland',
        CK: 'Cook Islands',
        CL: 'Chile',
        CN: 'China',
        CO: 'Colombia',
        CR: 'Costa Rica',
        CS: 'Serbia And Montenegro',
        CY: 'Cyprus',
        CZ: 'Czech Republic',
        DE: 'Germany',
        DK: 'Denmark',
        DO: 'Dominican Republic',
        DZ: 'Algeria',
        EC: 'Ecuador',
        EE: 'Estonia',
        EG: 'Egypt',
        ES: 'Spain',
        FI: 'Finland',
        FJ: 'Fiji',
        FR: 'France',
        GB: 'United Kingdom',
        GR: 'Greece',
        GT: 'Guatemala',
        HK: 'Hong Kong',
        HN: 'Honduras',
        HR: 'Croatia',
        HU: 'Hungary',
        ID: 'Indonesia',
        IE: 'Ireland',
        IL: 'Israel',
        IN: 'India',
        IQ: 'Iraq',
        IS: 'Iceland',
        IT: 'Italy',
        JM: 'Jamaica',
        JO: 'Jordan',
        JP: 'Japan',
        KW: 'Kuwait',
        LB: 'Lebanon',
        LT: 'Lithuania',
        LU: 'Luxembourg',
        LV: 'Latvia',
        MA: 'Morocco',
        MK: 'Macedonia',
        MT: 'Malta',
        MX: 'Mexico',
        MY: 'Malaysia',
        NI: 'Nicaragua',
        NL: 'Netherlands',
        NO: 'Norway',
        NZ: 'New Zealand',
        OM: 'Oman',
        PA: 'Panama',
        PE: 'Peru',
        PG: 'Papua New Guinea',
        PH: 'Philippines',
        PL: 'Poland',
        PR: 'Puerto Rico',
        PT: 'Portugal',
        PY: 'Paraguay',
        QA: 'Qatar',
        RO: 'Romania',
        RU: 'Russian Federation',
        SA: 'Saudi Arabia',
        SB: 'Solomon Islands',
        SD: 'Sudan',
        SE: 'Sweden',
        SG: 'Singapore',
        SI: 'Slovenia',
        SK: 'Slovakia',
        SV: 'El Salvador',
        SY: 'Syrian Arab Republic',
        TH: 'Thailand',
        TN: 'Tunisia',
        TO: 'Tonga',
        TR: 'Turkey',
        TW: 'Taiwan',
        UA: 'Ukraine',
        US: 'United States',
        UY: 'Uruguay',
        VE: 'Venezuela',
        VN: 'Viet Nam',
        VU: 'Vanuatu',
        WS: 'Samoa',
        YE: 'Yemen',
        ZA: 'South Africa',
    },
    usRegion: {
        MW: 'Midwest',
        NE: 'Northeast',
        SE: 'Southeast',
        SW: 'Southwest',
        W: 'West',
    },
    currency: {
        ALL: 'Albania, Leke',
        DZD: 'Algeria, Dinars',
        ARS: 'Argentina, Pesos',
        AUD: 'Australia, Dollars',
        BHD: 'Bahrain, Dinars',
        BYR: 'Belarus, Rubles',
        BOB: 'Bolivia, Bolivianos',
        BAM: 'Bosnia and Herzegovina, Convertible Marka',
        BRL: 'Brazil, Real',
        CAD: 'Canada, Dollars',
        CLP: 'Chile, Pesos',
        CNY: 'China, Yuan Renminbi',
        COP: 'Colombia, Pesos',
        CRC: 'Costa Rica, Colones',
        HRK: 'Croatia, Kuna',
        CZK: 'Czech Republic, Koruny',
        DKK: 'Denmark, Kroner',
        DOP: 'Dominican Republic, Pesos',
        EGP: 'Egypt, Pounds',
        EUR: 'Euro',
        GTQ: 'Guatemala, Quetzales',
        HNL: 'Honduras, Lempiras',
        HKD: 'Hong Kong, Dollars',
        HUF: 'Hungary, Forint',
        ISK: 'Iceland, Kronur',
        INR: 'India, Rupees',
        IDR: 'Indonesia, Rupiahs',
        IQD: 'Iraq, Dinars',
        ILS: 'Israel, New Shekels',
        JPY: 'Japan, Yen',
        JOD: 'Jordan, Dinars',
        KWD: 'Kuwait, Dinars',
        LVL: 'Latvia, Lati',
        LBP: 'Lebanon, Pounds',
        LTL: 'Lithuania, Litai',
        MKD: 'Macedonia, Denars',
        MYR: 'Malaysia, Ringgits',
        MXN: 'Mexico, Pesos',
        MAD: 'Morocco, Dirhams',
        NZD: 'New Zealand, Dollars',
        NIO: 'Nicaragua, Cordobas',
        NOK: 'Norway, Kroner',
        OMR: 'Oman, Rials',
        PAB: 'Panama, Balboa',
        PYG: 'Paraguay, Guarani',
        PEN: 'Peru, Nuevos Soles',
        PHP: 'Philippines, Pesos',
        PLN: 'Poland, Zlotych',
        QAR: 'Qatar, Rials',
        RON: 'Romania, New Lei',
        RUB: 'Russia, Rubles',
        SAR: 'Saudi Arabia, Riyals',
        RSD: 'Serbia, Dinars',
        SGD: 'Singapore, Dollars',
        ZAR: 'South Africa, Rand',
        SDG: 'Sudan, Pounds',
        SEK: 'Sweden, Kronor',
        CHF: 'Switzerland, Francs',
        SYP: 'Syria, Pounds',
        TWD: 'Taiwan, New Dollars',
        THB: 'Thailand, Baht',
        TND: 'Tunisia, Dinars',
        TRY: 'Turkey, Lira',
        UAH: 'Ukraine, Hryvnia',
        AED: 'United Arab Emirates, Dirhams',
        GBP: 'United Kingdom, Pounds',
        USD: 'United States of America, Dollars',
        UYU: 'Uruguay, Pesos',
        VEF: 'Venezuela, Bolivares Fuertes',
        VND: 'Viet Nam, Dong',
        YER: 'Yemen, Rials',
    },
    lang: {
        ALB: 'Albanian',
        ARA: 'Arabic',
        BEL: 'Belarussian',
        BUL: 'Bulgarian',
        CAT: 'Catalan',
        CHI: 'Chinese',
        SCR: 'Croatian',
        CZE: 'Czech',
        DAN: 'Danish',
        DUT: 'Dutch',
        ENG: 'English',
        FIN: 'Finnish',
        FRE: 'French',
        GER: 'German',
        GRE: 'Greek',
        HEB: 'Hebrew',
        HIN: 'Hindi',
        HUN: 'Hungarian',
        IND: 'Indonesian',
        GLE: 'Irish',
        ITA: 'Italian',
        JPN: 'Japanese',
        LAV: 'Latvian',
        LIT: 'Lithuanian',
        MAC: 'Macedonian',
        MAY: 'Malay',
        MLT: 'Maltese',
        NOR: 'Norwegian',
        POL: 'Polish',
        POR: 'Portuguese',
        RUM: 'Romanian',
        RUS: 'Russian',
        SCC: 'Serbian',
        SLO: 'Slovak',
        SPA: 'Spanish',
        THA: 'Thai',
        TUR: 'Turkish',
        UKR: 'Ukrainian',
        VIE: 'Vietnamese',
    },
    region: {
        NCSA: 'Americas',
        EU: 'European Union',
        EMEA: 'Europe; Middle East; Africa',
        APJ: 'Asia Pacific; Japan',
    },
    caProvince: {
        AB: 'Alberta',
        BC: 'Colombie-Britannique',
        PE: 'Île-du-Prince-Édouard',
        MB: 'Manitoba',
        NB: 'Nouveau-Brunswick',
        NS: 'Nouvelle-Écosse',
        NU: 'Nunavut',
        ON: 'Ontario',
        QC: 'Québec',
        SK: 'Saskatchewan',
        NL: 'Terre-Neuve-et-Labrador',
        YT: 'Yukon',
        NT: 'Territoires du Nord-Ouest',
    },
    caRegion: {
        QC: 'Québec',
        HQ: 'Hors Québec',
    },
}
