/* Generated By:JavaCC: Do not edit this line. BExGrammarConstants.java */
package org.openl.grammar.bexgrammar;

public interface BExGrammarConstants {

  int EOF = 0;
  int OR = 6;
  int AND = 7;
  int NOT = 8;
  int ABSTRACT = 9;
  int BREAK = 10;
  int CALCULATE = 11;
  int CASE = 12;
  int CATCH = 13;
  int CONST = 14;
  int CONTINUE = 15;
  int _DEFAULT = 16;
  int DO = 17;
  int ELSE = 18;
  int EXTENDS = 19;
  int FALSE = 20;
  int FINAL = 21;
  int FINALLY = 22;
  int FOR = 23;
  int GOTO = 24;
  int IF = 25;
  int PLUSSTR = 26;
  int IMPLEMENTS = 27;
  int IMPORT = 28;
  int INSTANCEOF = 29;
  int INTERFACE = 30;
  int NATIVE = 31;
  int NEW = 32;
  int NULL = 33;
  int PACKAGE = 34;
  int PRIVATE = 35;
  int PROTECTED = 36;
  int PUBLIC = 37;
  int RETURN = 38;
  int STATIC = 39;
  int SUPER = 40;
  int SWITCH = 41;
  int SYNCHRONIZED = 42;
  int THROW = 43;
  int THROWS = 44;
  int TRANSIENT = 45;
  int TRUE = 46;
  int TRY = 47;
  int VOID = 48;
  int VOLATILE = 49;
  int WHILE = 50;
  int OF = 51;
  int THE = 52;
  int WHERE = 53;
  int IS = 54;
  int LESS = 55;
  int THAN = 56;
  int LPAREN = 57;
  int RPAREN = 58;
  int LBRACE = 59;
  int RBRACE = 60;
  int LBRACKET = 61;
  int RBRACKET = 62;
  int SEMICOLON = 63;
  int COMMA = 64;
  int DOT = 65;
  int DDOT = 66;
  int TDOT = 67;
  int ASSIGN = 68;
  int GT = 69;
  int STRICT_GT = 70;
  int LT = 71;
  int STRICT_LT = 72;
  int BANG = 73;
  int TILDE = 74;
  int HOOK = 75;
  int COLON = 76;
  int EQ = 77;
  int STRICT_EQ = 78;
  int LE = 79;
  int STRICT_LE = 80;
  int GE = 81;
  int STRICT_GE = 82;
  int NE = 83;
  int STRICT_NE = 84;
  int BOOL_OR = 85;
  int BOOL_AND = 86;
  int INCR = 87;
  int DECR = 88;
  int PLUS = 89;
  int MINUS = 90;
  int STAR = 91;
  int SLASH = 92;
  int BIT_AND = 93;
  int BIT_OR = 94;
  int BIT_XOR = 95;
  int REM = 96;
  int LSHIFT = 97;
  int RSIGNEDSHIFT = 98;
  int RUNSIGNEDSHIFT = 99;
  int PLUSASSIGN = 100;
  int MINUSASSIGN = 101;
  int STARASSIGN = 102;
  int SLASHASSIGN = 103;
  int ANDASSIGN = 104;
  int ORASSIGN = 105;
  int XORASSIGN = 106;
  int REMASSIGN = 107;
  int LSHIFTASSIGN = 108;
  int RSIGNEDSHIFTASSIGN = 109;
  int RUNSIGNEDSHIFTASSIGN = 110;
  int EXP = 111;
  int IMPL = 112;
  int INTEGER_LITERAL = 113;
  int DECIMAL_LITERAL = 114;
  int HEX_LITERAL = 115;
  int OCTAL_LITERAL = 116;
  int FP_LITERAL1 = 117;
  int FP_LITERAL2 = 118;
  int FLOATING_POINT_LITERAL = 119;
  int BUSINESS_INTEGER_LITERAL = 120;
  int DATE_FORMAT_LITERAL_4_2_2 = 121;
  int TIME_FORMAT_LITERAL = 122;
  int PERCENT_LITERAL = 123;
  int EXPONENT = 124;
  int CHARACTER_LITERAL = 125;
  int STRING_LITERAL = 126;
  int IDENTIFIER = 127;
  int LETTER = 128;
  int DIGIT = 129;
  int LABEL = 130;
  int SINGLE_LINE_COMMENT = 133;
  int FORMAL_COMMENT = 134;
  int MULTI_LINE_COMMENT = 135;

  int DEFAULT = 0;
  int IN_FORMAL_COMMENT = 1;
  int IN_MULTI_LINE_COMMENT = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"abstract\"",
    "\"break\"",
    "\"Calculate\"",
    "\"case\"",
    "\"catch\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"plus\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"interface\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"of\"",
    "\"the\"",
    "\"where\"",
    "\"is\"",
    "\"less\"",
    "\"than\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"..\"",
    "\"...\"",
    "\"=\"",
    "\">\"",
    "\">==\"",
    "\"<\"",
    "\"<==\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"====\"",
    "\"<=\"",
    "\"<===\"",
    "\">=\"",
    "\">===\"",
    "\"!=\"",
    "\"!===\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"**\"",
    "\"->\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FP_LITERAL1>",
    "<FP_LITERAL2>",
    "<FLOATING_POINT_LITERAL>",
    "<BUSINESS_INTEGER_LITERAL>",
    "<DATE_FORMAT_LITERAL_4_2_2>",
    "<TIME_FORMAT_LITERAL>",
    "<PERCENT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<LABEL>",
    "<token of kind 131>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 136>",
    "\"equals to\"",
    "\"is same as\"",
    "\"does not equal to\"",
    "\"is different from\"",
    "\"is less than\"",
    "\"is more than\"",
    "\"is less or equal\"",
    "\"is no more than\"",
    "\"is in\"",
    "\"is more or equal\"",
    "\"is no less than\"",
    "\"less than\"",
    "\"more than\"",
    "\"or less\"",
    "\"and more\"",
  };

}
