interface DataType {
    key: React.Key;
    privilege: string;
    administrators: string;
    analysts: string;
    deployers: string;
    developers: string;
    testers: string;
    viewers: string;
}


const CreateGroupDataSource: DataType[] = [
    {
        key: "View projects",
        privilege: "View projects",
        administrators: "",
        analysts: "✓",
        deployers: "✓",
        developers: "✓",
        testers: "✓",
        viewers: "✓",
        
    },
    {
        key: "Create projects",
        privilege: "Create projects",
        administrators: "",
        analysts: "✓",
        deployers: "",
        developers: "✓",
        testers: "",
        viewers: "",
    },
    {
        key: "Edit projects",
        privilege: "Edit projects",
        administrators: "",
        analysts: "✓",
        deployers: "",
        developers: "✓",
        testers: "",
        viewers: "",
    },
    {
        key: "Erase projects",
        privilege: "Erase projects",
        administrators: "",
        analysts: "✓",
        deployers: "",
        developers: "✓",
        testers: "",
        viewers: "",
    },
    {
        key: "Delete projects",
        privilege: "Delete projects",
        administrators: "",
        analysts: "✓",
        deployers: "",
        developers: "✓",
        testers: "",
        viewers: "",
    },
    {
        key: "Unlock projects",
        privilege: "Unlock projects",
        administrators: "",
        analysts: "",
        deployers: "",
        developers: "",
        testers: "",
        viewers: "",
    },
    {
        key: "Deploy projects",
        privilege: "Deploy projects",
        administrators: "",
        analysts: "",
        deployers: "✓",
        developers: "",
        testers: "",
        viewers: "",
    },
    {
        key: "Create deploy configuration",
        privilege: "Create deploy configuration",
        administrators: "",
        analysts: "",
        deployers: "✓",
        developers: "",
        testers: "",
        viewers: "",
    },
    {
        key: "Edit deploy configuration",
        privilege: "Edit deploy configuration",
        administrators: "",
        analysts: "",
        deployers: "✓",
        developers: "",
        testers: "",
        viewers: "",
    },
    {
        key: "Delete deploy configuration",
        privilege: "Delete deploy configuration",
        administrators: "",
        analysts: "",
        deployers: "✓",
        developers: "",
        testers: "",
        viewers: "",
    },
    {
        key: "Erase deploy configuration",
        privilege: "Erase deploy configuration",
        administrators: "",
        analysts: "",
        deployers: "✓",
        developers: "",
        testers: "",
        viewers: "",
    },
    {
        key: "Unlock deploy configuration",
        privilege: "Unlock deploy configuration",
        administrators: "",
        analysts: "",
        deployers: "",
        developers: "",
        testers: "",
        viewers: "",
    }, {
        key: "Create tables",
        privilege: "Create tables",
        administrators: "",
        analysts: "✓",
        deployers: "",
        developers: "✓",
        testers: "",
        viewers: "",
    },
    {
        key: "Edit tables",
        privilege: "Edit tables",
        administrators: "",
        analysts: "✓",
        deployers: "",
        developers: "✓",
        testers: "",
        viewers: "",
    },
    {
        key: "Remove tables",
        privilege: "Remove tables",
        administrators: "",
        analysts: "✓",
        deployers: "",
        developers: "✓",
        testers: "",
        viewers: "",
    },
    {
        key: "Run tables",
        privilege: "Run tables",
        administrators: "",
        analysts: "✓",
        deployers: "",
        developers: "",
        testers: "✓",
        viewers: "",
    },
    {
        key: "Trace tables",
        privilege: "Trace tables",
        administrators: "",
        analysts: "✓",
        deployers: "",
        developers: "",
        testers: "✓",
        viewers: "",
    },
    {
        key: "Benchamark tables",
        privilege: "Benchamark tables",
        administrators: "",
        analysts: "✓",
        deployers: "",
        developers: "",
        testers: "✓",
        viewers: "",
    }, {
        key: "Administrate",
        privilege: "Administrate",
        administrators: "✓",
        analysts: "",
        deployers: "",
        developers: "",
        testers: "",
        viewers: "",
    },
];
export default CreateGroupDataSource;