
interface DataType {
    key: React.Key;
    privilege: string;
    administrators: string;
    analysts: string;
    deployers: string;
    developers: string;
    testers: string;
    viewers: string;
}


const CreateGroupDataSource: DataType[] = [
    {
        key: "1",
        privilege: "View projects",
        administrators: "",
        analysts: "✓",
        deployers: "✓",
        developers: "✓",
        testers: "✓",
        viewers: "✓",
    },
    {
        key: "2",
        privilege: "Create projects",
        administrators: "",
        analysts: "✓",
        deployers: "",
        developers: "✓",
        testers: "",
        viewers: "",
    },
    {
        key: "3",
        privilege: "Edit projects",
        administrators: "",
        analysts: "✓",
        deployers: "",
        developers: "✓",
        testers: "",
        viewers: "",
    },
    {
        key: "4",
        privilege: "Erase projects",
        administrators: "",
        analysts: "✓",
        deployers: "",
        developers: "✓",
        testers: "",
        viewers: "",
    },
    {
        key: "5",
        privilege: "Delete projects",
        administrators: "",
        analysts: "✓",
        deployers: "",
        developers: "✓",
        testers: "",
        viewers: "",
    },
    {
        key: "6",
        privilege: "Unlock projects",
        administrators: "",
        analysts: "",
        deployers: "",
        developers: "",
        testers: "",
        viewers: "",
    },
    {
        key: "7",
        privilege: "Deploy projects",
        administrators: "",
        analysts: "",
        deployers: "✓",
        developers: "",
        testers: "",
        viewers: "",
    },
    {
        key: "8",
        privilege: "Create deploy configuration",
        administrators: "",
        analysts: "",
        deployers: "✓",
        developers: "",
        testers: "",
        viewers: "",
    },
    {
        key: "9",
        privilege: "Edit deploy configuration",
        administrators: "",
        analysts: "",
        deployers: "✓",
        developers: "",
        testers: "",
        viewers: "",
    },
    {
        key: "10",
        privilege: "Delete deploy configuration",
        administrators: "",
        analysts: "",
        deployers: "✓",
        developers: "",
        testers: "",
        viewers: "",
    },
    {
        key: "11",
        privilege: "Erase deploy configuration",
        administrators: "",
        analysts: "",
        deployers: "✓",
        developers: "",
        testers: "",
        viewers: "",
    },
    {
        key: "12",
        privilege: "Unlock deploy configuration",
        administrators: "",
        analysts: "",
        deployers: "",
        developers: "",
        testers: "",
        viewers: "",
    }, {
        key: "13",
        privilege: "Create tables",
        administrators: "",
        analysts: "✓",
        deployers: "",
        developers: "✓",
        testers: "",
        viewers: "",
    },
    {
        key: "14",
        privilege: "Edit tables",
        administrators: "",
        analysts: "✓",
        deployers: "",
        developers: "✓",
        testers: "",
        viewers: "",
    },
    {
        key: "15",
        privilege: "Remove tables",
        administrators: "",
        analysts: "✓",
        deployers: "",
        developers: "✓",
        testers: "",
        viewers: "",
    },
    {
        key: "16",
        privilege: "Run tables",
        administrators: "",
        analysts: "✓",
        deployers: "",
        developers: "",
        testers: "✓",
        viewers: "",
    },
    {
        key: "17",
        privilege: "Trace tables",
        administrators: "",
        analysts: "✓",
        deployers: "",
        developers: "",
        testers: "✓",
        viewers: "",
    },
    {
        key: "18",
        privilege: "Benchamark tables",
        administrators: "",
        analysts: "✓",
        deployers: "",
        developers: "",
        testers: "✓",
        viewers: "",
    }, {
        key: "19",
        privilege: "Administrate",
        administrators: "✓",
        analysts: "",
        deployers: "",
        developers: "",
        testers: "",
        viewers: "",
    },
];
export default CreateGroupDataSource;