# Default list of class for registering in the Jackson databinding.
ruleservice.databinding.rootClassNames =

### Define default rules for serialization/deserialization of the JSON objects in the REST services.
# Object mapper setting. options: ALWAYS, NON_NULL, NON_ABSENT, NON_EMPTY, NON_DEFAULT, USE_DEFAULTS
ruleservice.jackson.serializationInclusion = USE_DEFAULTS
# Object mapper setting. options: JAVA_LANG_OBJECT, OBJECT_AND_NON_CONCRETE, NON_CONCRETE_AND_ARRAYS, NON_FINAL, EVERYTHING, DISABLED
ruleservice.jackson.defaultTypingMode = JAVA_LANG_OBJECT
# Enables case insensitive matching of the JSON field names to the Java properties on deserialization.
ruleservice.jackson.caseInsensitiveProperties = false
# Identifier of whether deserialization fails when the JSON object contains a field that is unknown to the target type.
ruleservice.jackson.failOnUnknownProperties = false
# Identifier of whether serialization fails when an object has no properties to serialize.
ruleservice.jackson.failOnEmptyBeans = true
# Name of the JSON field that keeps the type information when default typing is enabled.
ruleservice.jackson.typingPropertyName = @class
# The value of this property is used as JsonTypeInfo.Id for all classes are used
# in ruleservice.databinding.rootClassNames and generated during rules compilation.
# options: NONE, CLASS, MINIMAL_CLASS, NAME, DEDUCTION
ruleservice.jackson.jsonTypeInfoId = NAME
# This property is deprecated, use ruleservice.jackson.jsonTypeInfoId=NAME instead
ruleservice.jackson.simpleClassNameAsTypingPropertyValue =

# Pattern used to serialize and deserialize the date values.
ruleservice.jackson.defaultDateFormat = yyyy-MM-dd'T'HH:mm:ss.SSS
