/* Generated By:JavaCC: Do not edit this line. BExGrammarConstants.java */
package org.openl.grammars.constexpr;

public interface BExGrammarConstants {

  int EOF = 0;
  int ABSTRACT = 6;
  int BREAK = 7;
  int CASE = 8;
  int CATCH = 9;
  int CONST = 10;
  int CONTINUE = 11;
  int _DEFAULT = 12;
  int DO = 13;
  int ELSE = 14;
  int EXTENDS = 15;
  int FALSE = 16;
  int FINAL = 17;
  int FINALLY = 18;
  int FOR = 19;
  int GOTO = 20;
  int IF = 21;
  int PLUSSTR = 22;
  int IMPLEMENTS = 23;
  int IMPORT = 24;
  int INSTANCEOF = 25;
  int INTERFACE = 26;
  int NATIVE = 27;
  int NEW = 28;
  int NULL = 29;
  int PACKAGE = 30;
  int PRIVATE = 31;
  int PROTECTED = 32;
  int PUBLIC = 33;
  int RETURN = 34;
  int STATIC = 35;
  int SUPER = 36;
  int SWITCH = 37;
  int SYNCHRONIZED = 38;
  int THROW = 39;
  int THROWS = 40;
  int TRANSIENT = 41;
  int TRUE = 42;
  int TRY = 43;
  int VOID = 44;
  int VOLATILE = 45;
  int WHILE = 46;
  int LPAREN = 47;
  int RPAREN = 48;
  int LBRACE = 49;
  int RBRACE = 50;
  int LBRACKET = 51;
  int RBRACKET = 52;
  int SEMICOLON = 53;
  int COMMA = 54;
  int DOT = 55;
  int ASSIGN = 56;
  int GT = 57;
  int LT = 58;
  int BANG = 59;
  int TILDE = 60;
  int HOOK = 61;
  int COLON = 62;
  int EQ = 63;
  int LE = 64;
  int GE = 65;
  int NE = 66;
  int SC_OR = 67;
  int SC_AND = 68;
  int INCR = 69;
  int DECR = 70;
  int PLUS = 71;
  int MINUS = 72;
  int STAR = 73;
  int SLASH = 74;
  int BIT_AND = 75;
  int BIT_OR = 76;
  int XOR = 77;
  int REM = 78;
  int LSHIFT = 79;
  int RSIGNEDSHIFT = 80;
  int RUNSIGNEDSHIFT = 81;
  int PLUSASSIGN = 82;
  int MINUSASSIGN = 83;
  int STARASSIGN = 84;
  int SLASHASSIGN = 85;
  int ANDASSIGN = 86;
  int ORASSIGN = 87;
  int XORASSIGN = 88;
  int REMASSIGN = 89;
  int LSHIFTASSIGN = 90;
  int RSIGNEDSHIFTASSIGN = 91;
  int RUNSIGNEDSHIFTASSIGN = 92;
  int EXP = 93;
  int IMPL = 94;
  int INTEGER_LITERAL = 95;
  int DECIMAL_LITERAL = 96;
  int HEX_LITERAL = 97;
  int OCTAL_LITERAL = 98;
  int FLOATING_POINT_LITERAL = 99;
  int BUSINESS_INTEGER_LITERAL = 100;
  int PERCENT_LITERAL = 101;
  int EXPONENT = 102;
  int CHARACTER_LITERAL = 103;
  int STRING_LITERAL = 104;
  int IDENTIFIER = 105;
  int LETTER = 106;
  int DIGIT = 107;
  int SINGLE_LINE_COMMENT = 110;
  int FORMAL_COMMENT = 111;
  int MULTI_LINE_COMMENT = 112;

  int DEFAULT = 0;
  int IN_FORMAL_COMMENT = 1;
  int IN_MULTI_LINE_COMMENT = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"abstract\"",
    "\"break\"",
    "\"case\"",
    "\"catch\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"plus\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"interface\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"**\"",
    "\"->\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<BUSINESS_INTEGER_LITERAL>",
    "<PERCENT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<token of kind 108>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 113>",
    "\"less than\"",
    "\"more than\"",
    "\"less or equal\"",
    "\"more or equal\"",
  };

}
