require "rake"

task default: :build

desc "Build the site"
task :build do
  sh "bundle exec jekyll build --profile --trace"
end

desc "Serve the site locally with live reload"
task :serve do
  sh "bundle exec jekyll serve --livereload"
end
